"use strict";
var moonChunk;var moonLod;var moonEntrances;var moonHeight;(function(){let DH=2463534242,EB=()=>{let x=DH;x^=x<<13;x^=x>>>17;x^=x<<5;DH=x;return x;},BA=target=>target.$clinit=()=>{},ES=obj=>{let cls=obj.constructor;let arrayDegree=0;while(cls[J]&&cls[J].item){++arrayDegree;cls=cls[J].item;}let clsName="";if(cls[J].primitiveKind!==0){clsName=cls[J].name;}else {clsName=cls[J]?cls[J].name||"a/"+cls.name:"@"+cls.name;}while(arrayDegree-->0){clsName+="[]";}return clsName;},H=superclass=>{if(superclass===0){return function()
{};}if(superclass===void 0){superclass=BN();}return function(){superclass.call(this);};},J=Symbol("teavm_meta"),BH=cls=>{if(cls[J].classObject===null){cls[J].classObject=EG(cls);}return cls[J].classObject;},BN=()=>G,Cl=source=>{return Object.assign({name:null,binaryName:null,parent:null,superinterfaces:[],modifiers:0,primitiveKind:0,itemType:null,arrayType:null,enclosingClass:null,declaringClass:null,simpleName:null,clinit:()=>{},constructor:null,enumConstants:()=>null,resolvedEnumConstants:null,reflection:
null,classObject:null,assignableCache:null,valueToObject:o=>o,objectToValue:o=>o},source||{});},Bj=(name,binaryName,kind,config)=>{let cls=()=>{};let meta=Cl({name:name,binaryName:binaryName,modifiers:1|1<<4,primitiveKind:kind});cls[J]=meta;if(typeof config==='function'){config(meta);}return cls;},CD=Bj("boolean","Z",1,meta=>{}),DZ=Bj("byte","B",2,meta=>{}),EO=Bj("short","S",3,meta=>{}),CP=Bj("char","C",4,meta=>{}),B_=Bj("int","I",5,meta=>{}),DG=Bj("long","J",6,meta=>{{meta.valueToObject=o=>Ck(o);}}),DM=Bj("float",
"F",7,meta=>{}),Cp=Bj("double","D",8,meta=>{}),BF=(a,b)=>a===b?0:a<b? -1:1,Z=Math.imul||function(a,b){let ah=a>>>16&0xFFFF;let al=a&0xFFFF;let bh=b>>>16&0xFFFF;let bl=b&0xFFFF;return al*bl+(ah*bl+al*bh<<16>>>0)|0;},Ci=(a,b)=>(a>>>0)/(b>>>0)>>>0,EW=(a,b)=>(a>>>0)%(b>>>0)>>>0,CF=(a,b)=>{a>>>=0;b>>>=0;return a<b? -1:a>b?1:0;},BQ=BigInt(0),U=(lo,hi)=>BigInt.asIntN(64,BigInt.asUintN(64,BigInt(lo))|BigInt.asUintN(64,BigInt(hi)<<BigInt(32))),R=val=>BigInt.asIntN(64,BigInt(val|0)),D1=val=>BigInt.asIntN(64,BigInt(val
>=0?Math.floor(val):Math.ceil(val))),E1=val=>Number(val),DY=val=>Number(BigInt.asIntN(64,val>>BigInt(32)))|0,Bh=val=>Number(BigInt.asIntN(32,val))|0,CW=(a,b)=>a===b,DU=(a,b)=>a>b,Eb=(a,b)=>a<b,BD=(a,b)=>BigInt.asIntN(64,a+b),E4=a=>BigInt.asIntN(64, -a),Bb=(a,b)=>BigInt.asIntN(64,a*b),Ej=(a,b)=>BigInt.asIntN(64,a/b),CL=(a,b)=>BigInt.asIntN(64,a&b),Br=(a,b)=>BigInt.asIntN(64,a^b),DC=(a,b)=>BigInt.asIntN(64,a<<BigInt(b&63)),B2=(a,b)=>BigInt.asIntN(64,BigInt.asUintN(64,a)>>BigInt(b&63)),Bf=(cls,sz)=>{let data=new Array(sz);data.fill(null);return new (O(cls))(data);},EZ
=(cls,sz)=>new (O(cls))(new Array(sz)),E3=sz=>new DV(new BigInt64Array(sz)),B1=sz=>new ER(new Uint16Array(sz)),Eg=sz=>new EJ(new Int8Array(sz)),Bt=sz=>new Ez(new Int16Array(sz)),Bi=sz=>new DI(new Int32Array(sz)),Ew=data=>{let buffer=new Int32Array(data.length);buffer.set(data);return new DI(buffer);},E2=sz=>new Er(new Int8Array(sz));
let Dc=sz=>new Ei(new Float32Array(sz)),X=sz=>new Dr(new Float64Array(sz)),Bn=data=>{let buffer=new Float64Array(data.length);buffer.set(data);return new Dr(buffer);},O=cls=>{let result=cls[J].arrayType;if(result===null){function JavaArray(data){(BN()).call(this);this.data=data;}JavaArray.prototype=Object.create((BN()).prototype);JavaArray.prototype.type=cls;JavaArray.prototype.constructor=JavaArray;JavaArray.prototype.toString=function(){let str="[";for(let i=0;i<this.data.length;++i){if(i>0){str+=", ";}str
+=this.data[i].toString();}str+="]";return str;};JavaArray.prototype.cu=function(){let dataCopy;if('slice' in this.data){dataCopy=this.data.slice();}else {dataCopy=new this.data.constructor(this.data.length);for(let i=0;i<dataCopy.length;++i){dataCopy[i]=this.data[i];}}return new (O(this.type))(dataCopy);};let name="["+cls[J].binaryName;JavaArray[J]=Cl({name:name,binaryName:name,parent:BN(),itemType:cls});result=JavaArray;cls[J].arrayType=JavaArray;}return result;},Cz=(cls,dimensions)=>{let first=0;for(let i
=dimensions.length -1;i>=0;i=i -1|0){if(dimensions[i]===0){first=i;break;}}if(first>0){for(let i=0;i<first;i=i+1|0){cls=O(cls);}if(first===dimensions.length -1){return Bf(cls,dimensions[first]);}}let arrays=new Array(B$(dimensions,first));let firstDim=dimensions[first]|0;for(let i=0;i<arrays.length;i=i+1|0){arrays[i]=Bf(cls,firstDim);}return BS(cls,arrays,dimensions,first,0);},Ch=dimensions=>{let arrays=new Array(B$(dimensions,0));if(arrays.length===0){return Cz(CD,dimensions);}let firstDim=dimensions[0]|0;for
(let i=0;i<arrays.length;i=i+1|0){arrays[i]=E2(firstDim);}return BS(CD,arrays,dimensions,0);},Et=dimensions=>{let arrays=new Array(B$(dimensions,0));if(arrays.length===0){return Cz(B_,dimensions);}let firstDim=dimensions[0]|0;for(let i=0;i<arrays.length;i=i+1|0){arrays[i]=Bi(firstDim);}return BS(B_,arrays,dimensions,0);},Cq=dimensions=>{let arrays=new Array(B$(dimensions,0));if(arrays.length===0){return Cz(Cp,dimensions);}let firstDim=dimensions[0]|0;for(let i=0;i<arrays.length;i=i+1|0){arrays[i]=X(firstDim);}return BS(Cp,
arrays,dimensions,0);},B$=(dimensions,start)=>{let val=dimensions[start+1]|0;for(let i=start+2;i<dimensions.length;i=i+1|0){val=val*(dimensions[i]|0)|0;if(val===0){break;}}return val;},BS=(cls,arrays,dimensions,start)=>{let limit=arrays.length;for(let i=start+1|0;i<dimensions.length;i=i+1|0){cls=O(cls);let dim=dimensions[i];let index=0;let packedIndex=0;while(index<limit){let arr=EZ(cls,dim);for(let j=0;j<dim;j=j+1|0){arr.data[j]=arrays[index];index=index+1|0;}arrays[packedIndex]=arr;packedIndex=packedIndex
+1|0;}limit=packedIndex;}return arrays[0];};
function D7(array){return array.data.length;}
let Cv,EK=strings=>{Fd();Cv=new Array(strings.length);for(let i=0;i<strings.length;++i){Cv[i]=Du(Bk(strings[i]));}},P=index=>Cv[index],Dq=(array,offset,count)=>{let result="";let limit=offset+count;for(let i=offset;i<limit;i=i+1024|0){let next=Math.min(limit,i+1024|0);result+=String.fromCharCode.apply(null,array.subarray(i,next));}return result;},Bk=str=>str===null?null:Dd(str),Da=str=>str===null?null:str.bJ,Fd=()=>Bu(),Du;
{Du=str=>str;}let BU=(from,to)=>{if(from===to){return true;}let map=from[J].assignableCache;if(map===null){map=new Map();from[J].assignableCache=map;}let cachedResult=map.get(to);if(typeof cachedResult!=='undefined'){return cachedResult;}if(to[J].itemType!==null){let result=from[J].itemType!==null&&BU(from[J].itemType,to[J].itemType);map.set(to,result);return result;}let parent=from[J].parent;if(parent!==null&&parent!==from){if(BU(parent,to)){map.set(to,true);return true;}}let superinterfaces=from[J].superinterfaces;for
(let i=0;i<superinterfaces.length;i=i+1|0){if(BU(superinterfaces[i],to)){map.set(to,true);return true;}}map.set(to,false);return false;},L=ex=>{throw Fe(ex);},DR=Symbol("javaException"),Fe=ex=>{if(!ex.$jsException){C6(ex);}return ex.$jsException;},C6=ex=>{let javaCause=Fa(ex);let jsCause=javaCause!==null?javaCause.$jsException:void 0;let cause=typeof jsCause==="object"?{cause:jsCause}:void 0;let err=new Bg("Java exception thrown",cause);if(typeof Error.captureStackTrace==="function"){Error.captureStackTrace(err);}err[DR]
=ex;ex.$jsException=err;Es(err,ex);},Es=(err,ex)=>{if(typeof El==="function"&&err.stack){let stack=El(err.stack);let javaStack=Bf(EF(),stack.length);let elem;let noStack=false;for(let i=0;i<stack.length;++i){let element=stack[i];elem=EP(Bk(element.className),Bk(element.methodName),Bk(element.fileName),element.lineNumber);if(elem==null){noStack=true;break;}javaStack.data[i]=elem;}if(!noStack){E6(ex,javaStack);}}},Bg;
if(typeof Reflect==='object'){let defaultMessage=Symbol("defaultMessage");Bg=function Bg(message,cause){let self=Reflect.construct(Error,[void 0,cause],Bg);Object.setPrototypeOf(self,Bg.prototype);self[defaultMessage]=message;return self;}
;Bg.prototype=Object.create(Error.prototype,{constructor:{configurable:true,writable:true,value:Bg},message:{get(){try {let javaException=this[DR];if(typeof javaException==='object'){let javaMessage=DT(javaException);if(typeof javaMessage==="object"){return javaMessage!==null?javaMessage.toString():null;}}return this[defaultMessage];}catch(e){return "Exception occurred trying to extract Java exception message: "+e;}}}});}else {Bg=Error;}let DT=t=>E8(t),Fa=t=>Fc(t),EF=()=>BN(),EP=(className,methodName,fileName,
lineNumber)=>{{return null;}},E6=(e,stack)=>{},C7=null,DW=data=>{let i=0;let packages=new Array(data.length);for(let j=0;j<data.length;++j){let prefixIndex=data[i++];let prefix=prefixIndex>=0?packages[prefixIndex]:"";packages[j]=prefix+data[i++]+".";}C7=packages;},EN=[],Df=data=>{let packages=C7;let i=0;while(i<data.length){let cls=data[i++];EN.push(cls);let m=Cl();cls[J]=m;let className=data[i++];m.name=className!==0?className:null;if(m.name!==null){let packageIndex=data[i++];if(packageIndex>=0){m.name=packages[packageIndex]
+m.name;}}m.binaryName="L"+m.name+";";let superclass=data[i++];m.parent=superclass!==0?superclass:null;m.superinterfaces=data[i++];if(m.parent){cls.prototype=Object.create(m.parent.prototype);}else {cls.prototype={};}cls.prototype.constructor=cls;m.modifiers=data[i++];m.primitiveKind=0;let innerClassInfo=data[i++];if(innerClassInfo!==0){let enclosingClass=innerClassInfo[0];m.enclosingClass=enclosingClass!==0?enclosingClass:null;let declaringClass=innerClassInfo[1];m.declaringClass=declaringClass!==0?declaringClass
:null;let simpleName=innerClassInfo[2];m.simpleName=simpleName!==0?simpleName:null;}let clinit=data[i++];m.clinit=clinit!==0?()=>{m.clinit=()=>{};clinit();}:()=>{};let virtualMethods=data[i++];if(virtualMethods!==0){for(let j=0;j<virtualMethods.length;j+=2){let name=virtualMethods[j];let func=virtualMethods[j+1];if(typeof name==='string'){name=[name];}for(let k=0;k<name.length;++k){cls.prototype[name[k]]=func;}}}}};
function G(){this.$id$=0;}
let BW=a=>{return BH(Eq(a));},Eq=a=>{return a.constructor;},EY=a=>{let b,c,d,e,f,g,h,i,j,k;b=a;if(!b.$id$)b.$id$=EB();c=a.$id$;CH();if(!c)d=P(0);else{if(!c)e=32;else{f=0;e=c>>>16|0;if(e)f=16;else e=c;g=e>>>8|0;if(!g)g=e;else f=f|8;h=g>>>4|0;if(!h)h=g;else f=f|4;e=h>>>2|0;if(!e)e=h;else f=f|2;if(e>>>1|0)f=f|1;e=(32-f|0)-1|0;}i=(((32-e|0)+4|0)-1|0)/4|0;j=B1(i);k=j.data;i=(i-1|0)*4|0;e=0;while(i>=0){h=e+1|0;k[e]=Cm((c>>>i|0)&15,16);i=i-4|0;e=h;}d=Ef(j);}b=BK();Ba(Ba(b,P(1)),d);return BO(b);},BJ=H(0),BP=H(0),Cr
=H(0),Y=H(),D4=null,DE=null,ED=null,Bu=()=>{Bu=BA(Y);EI();},D2=(a,b)=>{Bu();a.bJ=Dq(b.data,0,b.data.length);},Ef=a=>{let b=new Y();D2(b,a);return b;},Ey=(a,b)=>{a.bJ=b;},Dd=a=>{let b=new Y();Ey(b,a);return b;},CC=(a,b)=>{let c;if(b>=0&&b<a.bJ.length)return a.bJ.charCodeAt(b);c=new B7;S(c);L(c);},Ct=(a,b,c)=>{let d,e,f;d=a.bJ.length;e=BF(b,c);if(!e)a=DE;else if(!(!b&&c==d)){if(b>=0&&e<=0&&c<=d)a=Dd(a.bJ.substring(b,c));else{f=new B7;S(f);L(f);}}return a;},Cy=b=>{Bu();return b===null?P(2):b;},EI=()=>{let b;D4
=B1(0);b=new Y;Bu();b.bJ="";DE=b;ED=new DN;},BL=H(),Dv=H(BL),EM=null,CH=()=>{CH=BA(Dv);EA();},EA=()=>{EM=BH(B_);};
function Cu(){let a=this;G.call(a);a.bK=null;a.bL=0;}
let Co=(a,b,c)=>{let d,e,f,g;d=a.bL;e=d-b|0;d=(d+c|0)-b|0;Dn(a,d);f=e-1|0;while(f>=0){g=a.bK.data;g[c+f|0]=g[b+f|0];f=f+(-1)|0;}a.bL=a.bL+(c-b|0)|0;},DQ=H(0),Dm=H(Cu),EX=a=>{a.bK=B1(16);},BK=()=>{let a=new Dm();EX(a);return a;},Ba=(a,b)=>{let c,d,e,f,g,h;c=a.bL;d=a;b=b===null?P(2):b;e=d;if(c>=0&&c<=e.bL){a:{if(b===null)b=P(2);else if(b.bJ.length?0:1)break a;f=e.bL+b.bJ.length|0;Dn(e,f);f=e.bL-1|0;while(f>=c){e.bK.data[f+b.bJ.length|0]=e.bK.data[f];f=f+(-1)|0;}e.bL=e.bL+b.bJ.length|0;f=0;while(f<b.bJ.length)
{g=e.bK.data;h=c+1|0;g[c]=CC(b,f);f=f+1|0;c=h;}}return a;}b=new B7;DO(b);L(b);},CV=(a,b)=>{let c,d,e,f,g,h,i,j;c=a.bL;d=1;if(b<0){d=0;b= -b|0;}a:{if(CF(b,10)<0){if(d)Co(a,c,c+1|0);else{Co(a,c,c+2|0);e=a.bK.data;f=c+1|0;e[c]=45;c=f;}a.bK.data[c]=Cm(b,10);}else{g=1;h=1;f=Ci((-1),10);b:{while(true){i=g*10|0;if(CF(i,b)>0){i=g;break b;}h=h+1|0;if(CF(i,f)>0)break;g=i;}}if(!d)h=h+1|0;Co(a,c,c+h|0);if(d)f=c;else{e=a.bK.data;f=c+1|0;e[c]=45;}while(true){if(!i)break a;e=a.bK.data;j=f+1|0;e[f]=Cm(Ci(b,i),10);b=EW(b,i);i
=Ci(i,10);f=j;}}}return a;},BO=a=>{let b,c,d,e,f;b=new Y;c=a.bK;d=c.data;e=a.bL;Bu();f=d.length;if(e>=0&&e<=(f-0|0)){b.bJ=Dq(c.data,0,e);return b;}b=new Bw;S(b);L(b);},Dn=(a,b)=>{let c,d,e,f;c=a.bK.data.length;if(c<b){b=c>=1073741823?2147483647:BB(b,BB(c*2|0,5));d=a.bK.data;e=B1(b);f=e.data;b=BZ(b,d.length);c=0;while(c<b){f[c]=d[c];c=c+1|0;}a.bK=e;}};
function Cg(){let a=this;G.call(a);a.ck=null;a.ct=null;a.cn=0;a.cl=0;}
let Fl=a=>{return a;},Dg=a=>{C6(a);},E8=a=>{return a.ck;},Fc=a=>{let b;b=a.ct;if(b===a)b=null;return b;},CE=H(Cg),Q=H(CE),S=a=>{Dg(a);a.cn=1;a.cl=1;},Fh=()=>{let a=new Q();S(a);return a;},Bc=(a,b)=>{Dg(a);a.cn=1;a.cl=1;a.ck=b;},Fi=a=>{let b=new Q();Bc(b,a);return b;},BI=H(),Ea=H(BI),DS=H(BI),CJ=H(0),Dy=H(0),C5=H(0);
function C3(){G.call(this);this.bP=null;}
let EG=b=>{let c;c=new C3;c.bP=b;return c;},B5=a=>{return !a.bP[J].primitiveKind?0:1;},Dh=a=>{let b;b=a.bP[J].itemType;return b===null?null:BH(b);},DK=H(),CM=null,CZ=BQ,Cj=null,Be=()=>{Be=BA(DK);D5();},Cc=b=>{let c,d,e;Be();a:{if(Cj!==null){c=CM;if(b===c)d=1;else if(!(c instanceof Y))d=0;else{c=c;d=b.bJ!==c.bJ?0:1;}if(d)break a;}CM=b;BE();if(b===null){b=new Bd;Bc(b,P(3));L(b);}e=DX(b,0,b.bJ.length,10);CZ=e;b=new Cn;V();b.cr=Bi(40);b.b9=E3(40);b.b1=X(40);b.bY=X(40);b.b0=X(40);b.bX=X(40);b.bZ=Bi(40);b.bV=X(3);c
=new CI;d=Db(16);c.bT=0;c.bM=Bf(Ca,d);c.cp=0.75;CQ(c);b.b3=c;b.cj=e;Cj=b;}return Cj;},B0=b=>{let c,d,e,f;Be();b=b.data;c=b.length;d=new Int16Array(c);e=0;while(e<c){f=b[e];d[e]=f;e=e+1|0;}return d;},DP=b=>{let c,d,e,f;Be();b=b.data;c=b.length;d=new Float32Array(c);e=0;while(e<c){f=b[e];d[e]=f;e=e+1|0;}return d;},Em=(b,c,d,e)=>{return {tops:b,mats:c,ring:d,runs:e};},D3=(b,c)=>{return {h:b,m:c};},C=(b,c,d)=>{let e,f;Be();b=Bk(b);e=c;f=d;b=Eh(Cc(b),CZ,e,f);return Em(B0(b.b7),B0(b.cc),B0(b.bQ),B0(b.cb));},D=(b,
c,d,e,f)=>{let g,h,i,j,k,l,m,n,o,p,q,r,s;Be();b=Bk(b);g=c;h=d;i=e;j=f;b=Cc(b);k=i+1|0;i=Z(k,k);l=Dc(i);m=l.data;n=Dc(i);o=n.data;p=0;while(p<k){q=0;while(q<k){i=g+Z(q,j)|0;r=h+Z(p,j)|0;s=Z(p,k)+q|0;m[s]=Bo(b,i,r);o[s]=CB(b,i,r);q=q+1|0;}p=p+1|0;}m=Bf(O(DM),2).data;m[0]=l;m[1]=n;return D3(DP(m[0]),DP(m[1]));},E=(b,c,d,e)=>{let f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ba,bb,bc;Be();b=Bk(b);f=c;g=d;h=e;b=Cc(b);i=Bi(24);j=0;k=f-h|0;l=T(k,176);m=f+h|0;n=T(m,176);o=g-h|0;p=T(o,176);q=g+h|0;r=T(q,176);s=h;while(l
<=n){t=p;while(t<=r){c=Dp(b,l,t);if(c!==Bm&&!(BC(c.bS-f|0,c.bR-g|0)>s)){u=i.data;v=j+3|0;w=u.length;if(v>w)i=BT(i,w*2|0);u=i.data;v=j+1|0;u[j]=c.bS;w=v+1|0;u[v]=c.bR;j=w+1|0;u[w]=Bh((Bq(c.cd)));}t=t+1|0;}l=l+1|0;}u=BT(i,j);x=Bi(30);t=0;r=Z(h,h);while(o<=q){p=k;while(p<=m){h=p-f|0;h=Z(h,h);j=o-g|0;if((h+Z(j,j)|0)<=r){y=0.0;j=1;while(j>=0){if(BY(b,p,o,j,b.bV)){i=b.bV.data;z=i[1];s=i[0];ba=p;bb=ba/7.0;bc=o;s=s+M(b,bb,bc/7.0,1,12+j|0)*0.3*z;y=N(y,K(0.42,0.62,M(b,ba/26.0,bc/26.0,1,16+j|0))*(1.0-K(0.45*z,1.2*z,s)));}j
=j+(-1)|0;}if(!(y<0.75)){j=0;l=0;a:{while(l<t){i=x.data;if(C_(i[l]-p|0)<22&&C_(i[l+1|0]-o|0)<22){j=1;break a;}l=l+3|0;}}if(!j){i=x.data;h=t+3|0;j=i.length;if(h>j)x=BT(x,j*2|0);i=x.data;h=t+1|0;i[t]=p;j=h+1|0;i[h]=o;t=j+1|0;i[j]=Bh((Bq(Bo(b,p,o))));}}}p=p+5|0;}o=o+5|0;}i=u.data;u=(BT(x,t)).data;f=i.length;g=f/3|0;h=u.length;x=Bi((g+(h/3|0)|0)*4|0).data;g=0;j=0;while(j<f){l=g+1|0;x[g]=0;g=l+1|0;x[l]=i[j];l=g+1|0;n=j+1|0;x[g]=i[n];g=l+1|0;x[l]=Bh((Bq(Bo(b,i[j],i[n]))));j=j+3|0;}j=0;while(j<h){f=g+1|0;x[g]=1;g=
f+1|0;x[f]=u[j];l=g+1|0;x[g]=u[j+1|0];g=l+1|0;x[l]=u[j+2|0];j=j+3|0;}f=x.length;b=new Int32Array(f);g=0;while(g<f){h=x[g];b[g]=h;g=g+1|0;}return b;},F=(b,c,d)=>{let e,f;Be();b=Bk(b);e=c;f=d;return Bo(Cc(b),e,f);},D5=()=>{return;},EU=H(),Eu=H(),E7=H(),DF=H(0),DN=H(),CA=H(),EL=null,E5=null,Cx=()=>{Cx=BA(CA);En();},Cm=(b,c)=>{Cx();if(c>=2&&c<=36&&b>=0&&b<c)return b<10?(48+b|0)&65535:((97+b|0)-10|0)&65535;return 0;},En=()=>{EL=BH(CP);E5=Bf(CA,128);},D0=H(),EH=H(),D6=H(),Eh=(b,c,d,e)=>{let f,g,h,i,j,k,l,m,n,o,p,
q,r,s,t;f=d*16|0;g=e*16|0;h=Eg(65536);i=h.data;j=0;while(j<256){d=j?Dt(j):1;a:{k=d<<24>>24;if(k){l=0;while(true){if(l>=256)break a;i[(j*256|0)+l|0]=k;l=l+1|0;}}}j=j+1|0;}m=new DA;m.ch=h;m.cg=g;m.ci=f;EE(b,c,f,g,m);m=new Dk;m.b7=Bt(256);m.cc=Bt(256);m.bQ=Bt(64);m.cb=Bt(0);n=0;o=Bt(3072);l=0;while(l<256){j=255;while(j>0&&!i[(j*256|0)+l|0]){j=j+(-1)|0;}k=i[(j*256|0)+l|0];h=m.b7;d=k!=4&&k!=5?(2*j|0)+2|0:(2*j|0)+1|0;h.data[l]=d<<16>>16;m.cc.data[l]=k<<16>>16;p=(-1);q=4;while(true){d=BF(q,j);if(d>0)break;r=d<0&&!i[(q
*256|0)+l|0]?1:0;if(r&&p<0)p=q;if(!r&&p>=0){h=o.data;d=n+1|0;e=d*3|0;k=h.length;if(e>k){s=Bt(k*2|0);C9(o,0,s,0,k);o=s;}h=o.data;e=n*3|0;h[e]=l<<16>>16;h[e+1|0]=p<<16>>16;h[e+2|0]=(q-1|0)<<16>>16;p=(-1);n=d;}q=q+1|0;}l=l+1|0;}d=n*3|0;i=Bt(d);m.cb=i;C9(o,0,i,0,d);t=0;p=f-1|0;e=f+16|0;k=g-1|0;n=g+16|0;while(t<16){i=m.bQ.data;j=g+t|0;i[t]=B8(b,p,j)<<16>>16;m.bQ.data[16+t|0]=B8(b,e,j)<<16>>16;i=m.bQ.data;d=32+t|0;j=f+t|0;i[d]=B8(b,j,k)<<16>>16;m.bQ.data[48+t|0]=B8(b,j,n)<<16>>16;t=t+1|0;}return m;},B8=(b,c,d)=>{let e,
f,g,h,i,j,k;e=Bo(b,c,d);f=Bv(e)|0;g=!(e-f>=0.5)?0:1;h=f-1|0;i=Ds();j=Do(b,c,d,i);if(j&&CT(i,h))g=0;if(g)return (2*f|0)+1|0;k=h;while(j&&k>=4&&CX(i,k,h)){k=k+(-1)|0;}return (2*k|0)+2|0;};
function Dk(){let a=this;G.call(a);a.b7=null;a.cc=null;a.bQ=null;a.cb=null;}
function Cn(){let a=this;G.call(a);a.cj=BQ;a.cr=null;a.b9=null;a.b1=null;a.bY=null;a.b0=null;a.bX=null;a.bZ=null;a.bV=null;a.cf=0.0;a.cs=0.0;a.cq=0.0;a.b3=null;}
let CR=null,CS=null,By=null,C0=null,CK=null,CY=null,De=null,Dx=null,C4=null,C$=null,C2=0,Cb=null,B3=null,Bm=null,V=()=>{V=BA(Cn);Ev();},BM=b=>{V();b=Bb(Br(b,B2(b,30)),U(484763065, 3210233709));b=Bb(Br(b,B2(b,27)),U(321982955, 2496678331));return Br(b,B2(b,31));},I=(b,c)=>{V();return E1(B2(BM(BD(b,Bb(R(c),U(2135587861, 2654435769)))),11))*1.1102230246251565E-16;},Bl=(a,b,c,d)=>{return BM(Br(Br(a.cj,BM(Bb(R(b),U(3652509721, 1663821211)))),BM(BD(Bb(R(c),U(2135587861, 2654435769)),Bb(R(d),U(668265295, 3266489917))))));},Dl
=b=>{V();return b*b*b*(b*(b*6.0-15.0)+10.0);},DD=(a,b,c,d)=>{let e,f,g,h,i,j,k,l,m,n,o;e=Bv(b)|0;f=Bv(c)|0;g=Dl(b-e);h=Dl(c-f);i=I(Bl(a,d,e,f),0);j=e+1|0;k=I(Bl(a,d,j,f),0);l=f+1|0;m=I(Bl(a,d,e,l),0);n=I(Bl(a,d,j,l),0);o=i+(k-i)*g;return (o+(m+(n-m)*g-o)*h)*2.0-1.0;},M=(a,b,c,d,e)=>{let f,g,h,i,j,k,l,m,n;f=Dj(e,8);V();g=Cb.data[f];h=B3.data[f];i=0.0;j=1.0;k=0.0;l=0;while(l<d){m=b*g-c*h;n=b*h+c*g;i=i+DD(a,m,n,e+(l*31|0)|0)*j;k=k+j;b=m*2.03;c=n*2.03;j=j*0.5;l=l+1|0;}return i/k;},K=(b,c,d)=>{let e;V();e=N(0.0,
Bx(1.0,(d-b)/(c-b)));return e*e*(3.0-2.0*e);},CB=(a,b,c)=>{return K(0.0,0.22, -M(a,b/650.0,c/650.0,3,1));},Bo=(a,b,c)=>{return Dw(a,b,c,null);},Dw=(a,b,c,d)=>{let e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x;e=CB(a,b,c);f=1.0-e;g=b;h=g/900.0;i=c;j=64.0+M(a,h,i/900.0,3,2)*9.0-e*6.0+M(a,g/70.0,i/70.0,4,3)*(1.6+5.4*f);k=g/360.0;h=i/360.0;l=Dj(7,8);m=Cb.data[l];n=B3.data[l];o=0.0;p=1.0;q=0.0;r=0;while(r<4){s=k*m-h*n;h=k*n+h*m;k=1.0-DJ(DD(a,s,h,4+(r*17|0)|0));o=o+k*k*p;q=q+p;k=s*2.1;h=h*2.1;p=p*0.5;r=r+1|0;}m=j+Cd(N(0.0,
o/q-0.56)/0.44,1.5)*46.0*f;if(e<=0.05)n=0.0;else{k=M(a,g/240.0,i/240.0,2,7)/0.045;j=K((-0.25),0.35,M(a,g/90.0,i/90.0,1,8));n=3.4*e*Bp( -k*k)*j;}if(e<0.3)j=0.0;else{t=T(b,190);l=T(c,190);o=0.0;r=(-1);while(r<=1){u=(-1);while(u<=1){v=t+r|0;w=l+u|0;x=Bl(a,107,v,w);if(!(I(x,0)>0.22)){h=(v+I(x,1))*190.0;f=(w+I(x,2))*190.0;j=26.0+30.0*I(x,3);j=BC(g-h,i-f)/j;if(!(j>2.4)){o=o+(2.5+4.5*I(x,4))*Bp( -j*j*1.6);if(I(x,5)<0.4&&j<0.14)o=o-1.8*(1.0-j/0.14);}}u=u+1|0;}r=r+1|0;}j=o*K(0.3,0.6,e);}return N(8.0,Bx(225.0,ET(a,b,
c,m+n+j+E$(a,b,c,e,d))+M(a,g/9.0,i/9.0,2,6)*0.7));},ET=(a,b,c,d)=>{let e,f,g,h,i,j,k,l,m,n,o,p,q,r,s;e=1;f=b;g=f/7.0;h=c;i=h/7.0;j=f/55.0;k=h/55.0;l=f/26.0;h=h/26.0;while(e>=0){if(BY(a,b,c,e,a.bV)){m=a.bV.data;f=m[1];n=m[2];o=m[0]+M(a,g,i,1,12+e|0)*0.3*f;p=1.6*f;if(!(o>=p)){q=1.0-K(0.5*f,p,o);d=d-(1.6+0.55*f)*K((-0.1),0.35,M(a,j,k,1,14+e|0))*q;r=K(0.42,0.62,M(a,l,h,1,16+e|0))*(1.0-K(0.45*f,1.2*f,o));if(r>0.0){s=N(n-0.65*f-0.5,d-46.0);if(s<d)d=d+(s-d)*r;}}}e=e+(-1)|0;}return d;},E$=(a,b,c,d,e)=>{let f,g,h,i,
j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ba,bb,bc,bd,be,bf,bg,bh;f=0;g=0;h=1.0-0.3*d;i=b;j=c;while(true){V();k=CR.data;if(g>=k.length)break;if(f>=40)break;l=k[g];m=T(b,l);n=T(c,l);o=CS.data[g]*(g<5?h:1.0);p=(-1);q=l;while(p<=1){r=(-1);while(r<=1){s=m+p|0;t=n+r|0;u=Bl(a,100+g|0,s,t);if(!(I(u,0)>o)&&f<40){v=q*(0.1+0.12*I(u,3));w=i-(s+I(u,1))*q;x=j-(t+I(u,2))*q;y=v*2.8;if(!(w*w+x*x>y*y)){a.cr.data[f]=g;a.b9.data[f]=u;a.b1.data[f]=v;a.bY.data[f]=w;a.b0.data[f]=x;a.bX.data[f]=I(u,4);z=f;while(z>0){ba=a.bX.data;k=a.bZ.data;bb
=z-1|0;if(!(ba[k[bb]]<ba[f]))break;k[z]=k[bb];z=z+(-1)|0;}a.bZ.data[z]=f;f=f+1|0;}}r=r+1|0;}p=p+1|0;}g=g+1|0;}bc=0.0;bd=0.0;be=0.0;bb=0;while(bb<f){bf=a.bZ.data[bb];u=a.b9.data[bf];q=D_(a.b0.data[bf],a.bY.data[bf]);bg=1.0+0.06*W(3.0*q+I(u,5)*6.28)+0.04*W(5.0*q+I(u,6)*6.28);k=a.bY.data;bh=k[bf]*k[bf];k=a.b0.data;bh=Bs(bh+k[bf]*k[bf])/(a.b1.data[bf]*bg);bg=bd*(1.0-0.92*(1.0-K(0.8,1.05,bh)));D8(a,bh,q,a.b1.data[bf],a.bX.data[bf],u,d);bc=bc+a.cf;bd=bg+a.cs;be=N(be,a.cq);bb=bb+1|0;}if(e!==null)e.data[0]=be;return bd
-bc;},D8=(a,b,c,d,e,f,g)=>{let h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ba,bb,bc,bd,be,bf,bg;h=Bx(1.0,e*(0.5+12.0/(d+6.0)));i=BF(d,14.0);j=Bx(34.0,i<=0?0.4*d:5.6*Cd(d/14.0,0.45));k=Bx(16.0,i<=0?N(0.35,0.075*d):1.05*Cd(d/14.0,0.75));l=g*K(0.2,0.6,e)*0.9;e=j*(1.0-0.6*h);m=1.0-l;n=e*m;e=k*(1.0-0.75*h);o=1.0-0.85*l;p=e*o;q=K(11.0,22.0,d);r=0.0;if(b<1.0){s=n*(1.0-b*b);if(b>=0.5){t=(b-0.5)/0.5;u=t*t*(3.0-2.0*t);v=t*3.0;w=Bv(v);n=n*(1.0-(0.6*u+0.4*(w+K(0.0,1.0,v-w))/3.0));}r=s+(n-s)*q;}x=(b-1.0)/(0.17*(1.0+1.5*h));y=
p*Bp( -x*x);z=N(b,1.0);s=1.0-h;ba=0.55*s;t=7.0*c;bb=1.0+ba*(0.6*W(t+I(f,7)*6.28)+0.4*W(13.0*c+I(f,8)*6.28));e=y+0.45*k*(1.0-0.8*h)*o*Cd(z,(-3.0))*(1.0-K(1.5,2.8,b))*N(0.2,bb);bc=K(120.0,200.0,d);if(d>=18.0){ba=K(18.0,30.0,d)*(1.0-bc);bd=b/0.11;e=e+ba*0.45*j*(1.0-0.5*h)*m*Bp( -bd*bd)*(1.0+0.25*W(5.0*c+I(f,9)*6.28));}if(d>=120.0){o=(b-0.5)/0.075;e=e+bc*0.45*j*(1.0-0.5*h)*m*Bp( -o*o)*(0.6+0.4*W(3.0*c+I(f,10)*6.28));}if(d>=240.0){m=K(240.0,320.0,d)*(1.0-0.35*h);be=Bx(40.0,0.09*d);bf=(b-1.2)/0.1;d=e+m*be*(0.35+0.65
*K((-0.3),0.45,0.7*W(4.0*c+I(f,11)*6.28)+0.3*W(9.0*c+I(f,12)*6.28)))*Bp( -bf*bf);bg=(b-1.65)/0.13;e=d+m*0.45*be*K((-0.3),0.45,0.6*W(3.0*c+I(f,13)*6.28)+0.4*W(t+I(f,14)*6.28))*Bp( -bg*bg);}a.cf=r;a.cs=e;a.cq=s*(1.0-K(1.0,2.6,N(b,0.7)));},Ds=()=>{let b,c,d,e,f;V();b=Bf(Cs,By.data.length+1|0);c=b.data;d=0;e=c.length;while(d<e){f=new Cs;f.bN=2147483647;f.bO=(-2147483648);c[d]=f;d=d+1|0;}return b;},CT=(b,c)=>{let d,e,f;V();b=b.data;d=b.length;e=0;while(e<d){f=b[e];if(f.bO==1000&&c>=f.bN)return 1;e=e+1|0;}return 0;},Bz
=(a,b,c,d)=>{return M(a,b/150.0,c/150.0,2,(20+(d<4?0:200)|0)+d|0);},BY=(a,b,c,d,e)=>{let f,g,h,i,j,k,l,m,n,o;f=d<4?0:200;g=b;h=g/210.0;i=c;j=M(a,h,i/210.0,2,(40+f|0)+d|0);k=K(CY.data[d],De.data[d],j);if(k<=0.0)return 0;l=Bz(a,g,i,d);m=Bz(a,b+2|0,i,d)-l;n=Bz(a,g,c+2|0,d)-l;h=Bs(m*m+n*n)/2.0;if(h<0.0015)return 0;o=e.data;o[0]=DJ(l)/h;o[1]=(Dx.data[d]+C4.data[d]*I(Bl(a,(50+f|0)+d|0,T(b,160),T(c,160)),0))*k*C$.data[d];n=By.data[d];e=CK.data;o[2]=n+M(a,g/e[d],i/e[d],d!=2&&d!=3?1:2,(60+f|0)+d|0)*C0.data[d];return 1;},Dp
=(a,b,c)=>{let d,e,f,g,h,i;d=Br(DC(R(b),32),CL(R(c),U(4294967295, 0)));e=a.b3;f=Ck(d);if(f===null)e=DB(e);else{g=C1(f);e=CN(e,f,g&(e.bM.data.length-1|0),g);}e=e===null?null:e.b5;if(e!==null)return e;f=Ed(a,b,c);h=a.b3;i=Ck(d);if(i===null){e=DB(h);if(e===null){h.bW=h.bW+1|0;e=DL(h,null,0,0);b=h.bT+1|0;h.bT=b;if(b>h.b$)C8(h);}}else{c=C1(i);b=c&(h.bM.data.length-1|0);e=CN(h,i,b,c);if(e===null){h.bW=h.bW+1|0;e=DL(h,i,b,c);b=h.bT+1|0;h.bT=b;if(b>h.b$)C8(h);}}e.b5=f;return f;},Ed=(a,b,c)=>{let d,e,f,g,h,i,j,k,l,m,
n,o,p,q,r,s,t,u,v;d=Bl(a,400,b,c);if(I(d,0)>=0.85)return Bm;e=(b+0.12+0.76*I(d,1))*176.0;f=(c+0.12+0.76*I(d,2))*176.0;g=BZ(By.data.length-1|0,I(d,3)*By.data.length|0);h=0;i=e;j=f;a:{while(true){if(h>=10)break a;k=Bz(a,i,j,g);l=(Bz(a,i+2.0,j,g)-k)/2.0;m=(Bz(a,i,j+2.0,g)-k)/2.0;n=l*l+m*m;if(n<1.0E-9)break;o=k*l/n;p=k*m/n;q=Bs(o*o+p*p);if(q<0.3)break a;if(q>30.0){q=30.0/q;o=o*q;p=p*q;}i=i-o;j=j-p;h=h+1|0;}return Bm;}if(BC(i-e,j-f)>70.0)return Bm;r=Bh((Bq(i)));s=Bh((Bq(j)));t=X(3);if(BY(a,r,s,g,t)){t=t.data;if(!(t[1]
<2.6)&&!(t[0]>t[1]*0.6)){i=Bo(a,r,s);u=N(0.0,i-11.0-2.0*I(d,4)-t[2]);if(!(u>45.0)&&!(i-(t[2]+u)<5.0)){v=new BX;v.bS=r;v.bR=s;v.ce=g;v.cm=u;v.cd=t[2]+u;v.ca=N(50.0,u*2.2);e=t[1]+1.5+1.5*I(d,5);v.co=e;v.b6=e+45.0;return v;}return Bm;}}return Bm;},Do=(a,b,c,d)=>{let e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ba,bb,bc;e=0;f=X(3);g=Bf(BX,9).data;h=0;i=T(b,176);j=T(c,176);k=(-1);while(k<=1){l=(-1);while(l<=1){m=Dp(a,i+k|0,j+l|0);if(m!==Bm&&BC(b-m.bS|0,c-m.bR|0)<N(m.ca,m.b6)){n=h+1|0;g[h]=m;h=n;}l=l+1|0;}k=k+1|0;}o
=f.data;k=0;while(true){V();if(k>=By.data.length)break;p=d.data[k];p.bN=2147483647;p.bO=(-2147483648);p.b8=0;if(!BY(a,b,c,k,f))i=0;else{i=g.length;h=0;while(h<i){m=g[h];if(m!==null&&m.ce==k){q=BC(b-m.bS|0,c-m.bR|0);r=m.ca;if(q<r){q=K(0.0,1.0,1.0-q/r);o[2]=o[2]+m.cm*q;o[1]=o[1]*(1.0+0.5*q);}}h=h+1|0;}i=o[0]<o[1]&&o[1]>=1.2?1:0;}if(i){s=o[0]/o[1];r=o[1]*0.65*Bs(N(0.0,1.0-s*s));if(!(r<0.8)){p.bN=BB(4,E_(o[2]-r)|0);p.bO=Bv(o[2]+r)|0;e=1;}}k=k+1|0;}t=d.data[C2];t.bN=2147483647;t.bO=(-2147483648);t.b8=0;q=1.7976931348623157E308;i
=g.length;h=0;r=b;u=r/20.0;v=c;w=v/20.0;x=r/7.0;y=v/7.0;z=r/4.0;ba=v/4.0;while(h<i){m=g[h];if(m!==null){bb=BC(b-m.bS|0,c-m.bR|0);if(!(bb>m.b6)){bc=N(0.0,bb+M(a,u,w,1,412)*5.5+M(a,x,y,2,410)*1.8-m.co);r=bc<=2.5?bc*3.5:8.75+(bc-2.5)*1.6;q=Bx(q,m.cd-2.0+r+M(a,z,ba,1,411)*1.2);}}h=h+1|0;}if(q<160.0){t.bN=BB(4,Bv(q)|0);t.bO=1000;e=1;}return e;},Ev=()=>{let b,c,d,e;CR=Ew([20,44,96,208,448,960,2200]);CS=Bn([0.85,0.7,0.55,0.45,0.4,0.35,0.3]);b=Bi(6);c=b.data;c[0]=30;c[1]=43;c[2]=38;c[3]=38;c[4]=19;c[5]=8;By=b;C0=Bn([11.0,
7.0,20.0,20.0,9.0,6.0]);CK=Bn([70.0,70.0,140.0,140.0,80.0,80.0]);CY=Bn([0.05,0.05,0.2,0.2,0.05,0.05]);De=Bn([0.32,0.32,0.47,0.47,0.32,0.32]);Dx=Bn([3.0,3.0,2.4,2.4,3.0,3.0]);C4=Bn([3.5,3.5,2.6,2.6,3.5,3.5]);C$=Bn([1.0,1.0,1.0,1.0,1.25,1.45]);C2=c.length;Cb=X(8);B3=X(8);d=0;while(d<8){e=0.31+d*0.39;Cb.data[d]=EC(e);B3.data[d]=W(e);d=d+1|0;}Bm=new BX;},Bw=H(Q),DO=a=>{S(a);},Fk=()=>{let a=new Bw();DO(a);return a;};
function B4(){BL.call(this);this.b2=BQ;}
let D$=null,BE=()=>{BE=BA(B4);EV();},Ck=b=>{let c;BE();c=new B4;c.b2=b;return c;},DX=(b,c,d,e)=>{let f,g,h,i,j,k,l,m;BE();if(e>=2&&e<=36){if(c==d){b=new Bd;Bc(b,P(4));L(b);}a:{f=0;b=b;switch(CC(b,c)){case 43:g=c+1|0;break a;case 45:f=1;g=c+1|0;break a;default:}g=c;}h=BQ;i=R(e);j=BD(R(1),Ej(U(4294967295, 2147483647),i));if(g==d){b=new Bd;S(b);L(b);}while(g<d){k=g+1|0;g=CC(b,g);g=g>=48&&g<=57?g-48|0:g>=97&&g<=122?(g-97|0)+10|0:g>=65&&g<=90?(g-65|0)+10|0:(-1);if(g<0){l=new Bd;b=Cy(Ct(b,c,d));m=BK();Ba(Ba(m,P(5)),
b);Bc(l,BO(m));L(l);}if(g>=e){l=new Bd;b=Cy(Ct(b,c,d));m=BK();Ba(Ba(CV(Ba(m,P(6)),e),P(7)),b);Bc(l,BO(m));L(l);}if(DU(h,j)){b=new Bd;Bc(b,P(8));L(b);}h=BD(Bb(i,h),R(g));if(Eb(h,BQ)){if(k==d&&CW(h,U(0, 2147483648))&&f)return U(0, 2147483648);l=new Bd;b=Cy(Ct(b,c,d));m=BK();Ba(Ba(m,P(9)),b);Bc(l,BO(m));L(l);}g=k;}if(f)h=E4(h);return h;}b=new Bd;l=BK();CV(Ba(l,P(10)),e);Bc(b,BO(l));L(b);},C1=a=>{let b;b=a.b2;BE();return Bh(b)^DY(b);},EV=()=>{D$=BH(DG);},CO=H(0);
function DA(){let a=this;G.call(a);a.ch=null;a.cg=0;a.ci=0;}
let CG=(a,b,c,d,e)=>{let f,g,h;f=a.ch;g=a.cg;h=a.ci;if(c>=0&&c<256)f.data[((c*256|0)+((d-g|0)*16|0)|0)+(b-h|0)|0]=e<<24>>24;},Ec=H(),Dt=b=>{if(b<=59)return 1;return b>=64?0:2;},EE=(b,c,d,e,f)=>{let g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ba,bb,bc,bd,be,bf,bg,bh,bi,bj,bk,bl,bm,bn,bo;g=Cq([18,18]).data;h=Cq([16,16]);i=h.data;j=X(1);k=j.data;l=0;while(l<18){m=0;while(m<18){if(l>=1&&l<=16&&m>=1&&m<=16){g[l].data[m]=Dw(b,(d+l|0)-1|0,(e+m|0)-1|0,j);i[l-1|0].data[m-1|0]=k[0];}else g[l].data[m]=Bo(b,(d+l|0)-1|0,(e+
m|0)-1|0);m=m+1|0;}l=l+1|0;}n=Et([16,16]);j=n.data;o=Cq([16,16]);p=o.data;q=Ch([16,16]);k=q.data;r=Ch([16,16]);i=r.data;s=Ds();t=0;while(t<16){u=0;while(u<16){v=d+t|0;w=e+u|0;x=t+1|0;y=g[x].data;z=u+1|0;ba=y[z];bb=Bv(ba)|0;bc=!(ba-bb>=0.5)?0:1;bd=bb-1|0;be=(g[t+2|0].data[z]-g[t].data[z])/2.0;bf=(g[x].data[u+2|0]-g[x].data[u])/2.0;bg=Bs(be*be+bf*bf);p[t].data[u]=bg;bh=!(CB(b,v,w)>0.5)?0:1;bi=bg>0.85?0:BB(1,BZ(4,Bh((Bq(3.4-bg*3.2+(BG(c,v,w,0)-0.5)*1.2)))));bj=Do(b,v,w,s);bk=bj&&CT(s,bd)?1:0;k[t].data[u]=bk;if
(bk)bc=0;bl=bi<=0?4:5;x=BB(bb+1|0,64);bm=1;while(bm<=x){bn=BF(bm,bb);if(bn>0)bo=0;else if(!bn)bo=!bc?0:bl;else{bn=bd-bm|0;bo=bn<bi?2:bh&&bn<(bi+4|0)?3:1;if(bj&&CX(s,bm,bd))bo=0;}if(bo!=Dt(bm))CG(f,v,bm,w,bo);bm=bm+1|0;}j[t].data[u]=bd;i[t].data[u]=bc;u=z;}t=t+1|0;}E0(b,c,d,e,n,o,q,r,h,f);},CX=(b,c,d)=>{let e,f,g,h,i;b=b.data;e=b.length;f=0;g=BF(c,4);d=BF(c,d);while(f<e){h=b[f];i=h.bO;if(i!=(-2147483648)&&g>=0){if(c>=h.bN&&c<=i)return 1;if(h.b8&&c>i&&d<=0)return 1;}f=f+1|0;}return 0;},E0=(b,c,d,e,f,g,h,i,j,k)=>
{let l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ba,bb,bc,bd;l=Ch([16,16]).data;m=1;while(m<15){n=1;while(n<15){a:{o=h.data;p=d+m|0;q=e+n|0;if(!o[m].data[n]&&!l[m].data[n]&&!(g.data[m].data[n]>0.9)){r=(!(M(b,p/45.0,q/45.0,1,90)>0.25)?0.0025:0.035)+0.07*j.data[m].data[n];if(!(BG(c,p,q,1)>=r)){s=BG(c,p,q,2)<0.25&&m>=2&&m<=13&&n>=2&&n<=13?2:1;p= -s|0;t=p;while(true){if(t>s)break a;u=p;while(u<=s){v=Bs(Z(t,t)+Z(u,u)|0);w=s;if(!(v>w+0.4)){x=m+t|0;y=n+u|0;if(!o[x].data[y]){r=w+0.8-v;z=d+x|0;ba=e+y|0;bb=Bh((Bq(r*(0.8+BG(c,z,ba,
3)*0.6))));bc=0;while(bc<bb){q=(f.data[x].data[y]+1|0)+bc|0;CG(k,z,q,ba,1);bc=bc+1|0;}l[x].data[y]=1;}}u=u+1|0;}t=t+1|0;}}}}n=n+1|0;}m=m+1|0;}bd=0;while(bd<16){z=0;while(z<16){if(!l[bd].data[z]&&!h.data[bd].data[z]&&!i.data[bd].data[z]&&!(g.data[bd].data[z]>0.6)){n=d+bd|0;s=e+z|0;if(BG(c,n,s,4)<0.02){p=f.data[bd].data[z]+1|0;CG(k,n,p,s,4);}}z=z+1|0;}bd=bd+1|0;}},BG=(b,c,d,e)=>{return I(BM(BD(BD(Bb(b,R(31)),Br(DC(R(c),32),CL(R(d),U(4294967295, 0)))),Bb(R(e),U(2135587861, 2654435769)))),0);},Eo=H(),Fg=(b,c,d,
e,f)=>{let g,h,i,j,k,l,m,n;if(b!==null&&d!==null){if(c>=0&&e>=0&&f>=0&&(c+f|0)<=B9(b)&&(e+f|0)<=B9(d)){a:{b:{if(b!==d){g=Dh(BW(b));h=Dh(BW(d));if(g!==null&&h!==null){if(g===h)break b;if(!B5(g)&&!B5(h)){i=b;j=0;k=c;while(j<f){c:{l=i.data;m=k+1|0;n=l[k];if(n!==null){n=BW(n);if(BU(n.bP,h.bP)){k=1;break c;}}k=0;}if(!k){BV(b,c,d,e,j);b=new B6;S(b);L(b);}j=j+1|0;k=m;}BV(b,c,d,e,f);return;}if(!B5(g))break a;if(B5(h))break b;else break a;}b=new B6;S(b);L(b);}}BV(b,c,d,e,f);return;}b=new B6;S(b);L(b);}b=new Bw;S(b);L(b);}d
=new Di;Bc(d,P(11));L(d);},C9=(b,c,d,e,f)=>{if(c>=0&&e>=0&&f>=0&&(c+f|0)<=B9(b)&&(e+f|0)<=B9(d)){BV(b,c,d,e,f);return;}b=new Bw;S(b);L(b);},BV=(b,c,d,e,f)=>{if(f!==0){if(typeof b.data.buffer!=='undefined'){d.data.set(b.data.subarray(c,c+f),e);}else if(b!==d||e<c){for(let i=0;i<f;i=i+1|0){d.data[e++]=b.data[c++];}}else {c=c+f|0;e=e+f|0;for(let i=0;i<f;i=i+1|0){d.data[ --e]=b.data[ --c];}}}},Ek=H(),W=b=>{return Math.sin(b);},EC=b=>{return Math.cos(b);},Bp=b=>{return Math.exp(b);},Bs=b=>{return Math.sqrt(b);},E_
=b=>{return Math.ceil(b);},Bv=b=>{return Math.floor(b);},Cd=(b,c)=>{return Ex(b,c);},Ex=(b,c)=>{return Math.pow(b,c);},D_=(b,c)=>{return Math.atan2(b,c);},Bq=b=>{return D1(b+Ee(b)*0.5);},T=(b,c)=>{let d;d=b/c|0;if((b^c)<0&&Z(d,c)!=b)d=d-1|0;return d;},Dj=(b,c)=>{let d;d=b%c|0;if((b^c)<0&&d)d=d+c|0;return d;},BZ=(b,c)=>{if(b<c)c=b;return c;},BB=(b,c)=>{if(b>c)c=b;return c;},E9=(b,c)=>{return Math.min(b,c);},Bx=(b,c)=>{return E9(b,c);},Ep=(b,c)=>{return Math.max(b,c);},N=(b,c)=>{return Ep(b,c);},C_=b=>{if(b<0)b
= -b|0;return b;},EQ=b=>{return Math.abs(b);},DJ=b=>{return EQ(b);},Ee=b=>{return Math.sign(b);},BC=(b,c)=>{return Bs(b*b+c*c);},Dz=H(0),Cf=H(),Cw=H(0);
function CI(){let a=this;Cf.call(a);a.bT=0;a.bM=null;a.bW=0;a.cp=0.0;a.b$=0;}
let Db=b=>{let c;if(b>=1073741824)return 1073741824;if(!b)return 16;c=b-1|0;b=c|c>>1;b=b|b>>2;b=b|b>>4;b=b|b>>8;return (b|b>>16)+1|0;},CQ=a=>{a.b$=a.bM.data.length*a.cp|0;},CN=(a,b,c,d)=>{let e,f,g;e=a.bM.data[c];while(e!==null){if(e.b4==d){a:{f=e.b_;if(b!==f){g=b;if(!(g===f?1:f instanceof B4&&CW(f.b2,g.b2)?1:0)){c=0;break a;}}c=1;}if(c)break;}e=e.bU;}return e;},DB=a=>{let b;b=a.bM.data[0];while(b!==null&&b.b_!==null){b=b.bU;}return b;},DL=(a,b,c,d)=>{let e,f,g;e=new Ca;f=null;e.b_=b;e.b5=f;e.b4=d;g=a.bM.data;e.bU
=g[c];g[c]=e;return e;},C8=a=>{let b,c,d,e,f,g,h,i;b=a.bM.data.length;b=Db(!b?1:b<<1);c=Bf(Ca,b);d=c.data;e=0;f=b-1|0;while(true){g=a.bM.data;if(e>=g.length)break;h=g[e];g[e]=null;while(h!==null){b=h.b4&f;i=h.bU;h.bU=d[b];d[b]=h;h=i;}e=e+1|0;}a.bM=c;CQ(a);},Fb=H(Q),Di=H(Q),D9=H(),B9=b=>{let c;c=(BW(b)).bP;if(c[J].itemType!==null)return D7(b);b=new BR;S(b);L(b);},B6=H(Q),Ff=H(),BT=(b,c)=>{let d,e,f,g;b=b.data;d=Bi(c);e=d.data;f=BZ(c,b.length);g=0;while(g<f){e[g]=b[g];g=g+1|0;}return d;};
function BX(){let a=this;G.call(a);a.bS=0;a.bR=0;a.ce=0;a.cd=0.0;a.cm=0.0;a.ca=0.0;a.co=0.0;a.b6=0.0;}
let BR=H(Q),Bd=H(BR);
function Cs(){let a=this;G.call(a);a.bN=0;a.bO=0;a.b8=0;}
let B7=H(Bw),CU=H(0);
function Ce(){let a=this;G.call(a);a.b_=null;a.b5=null;}
function Ca(){let a=this;Ce.call(a);a.b4=0;a.bU=null;}
DW([]);
Df([G,0,0,[],1,0,0,0,BJ,0,G,[],1537,0,0,0,BP,0,G,[],1537,0,0,0,Cr,0,G,[],1537,0,0,0,Y,0,G,[BJ,BP,Cr],17,0,()=>Bu(),0,BL,0,G,[BJ],1025,0,0,0,Dv,0,BL,[BP],1,0,()=>CH(),0,Cu,0,G,[BJ,Cr],0,0,0,0,DQ,0,G,[],1537,0,0,0,Dm,0,Cu,[DQ],1,0,0,0,Cg,0,G,[],1,0,0,0,CE,0,Cg,[],1,0,0,0,Q,0,CE,[],1,0,0,0,BI,0,G,[],1025,0,0,0,Ea,0,BI,[],17,0,0,0,DS,0,BI,[],17,0,0,0,CJ,0,G,[],1537,0,0,0,Dy,0,G,[CJ],1537,0,0,0,C5,0,G,[],1537,0,0,0,C3,0,G,[Dy,C5],17,0,0,0,DK,0,G,[],17,0,()=>Be(),0,EU,0,G,[],17,0,0,0,Eu,0,G,[],17,0,0,0,E7,0,G,[],
17,0,0,0,DF,0,G,[],1537,0,0,0,DN,0,G,[DF],1,0,0,0,CA,0,G,[BP],1,0,()=>Cx(),0,D0,0,G,[],17,0,0,0,EH,0,G,[],17,0,0,0,D6,0,G,[],16,0,0,0,Dk,0,G,[],16,0,0,0,Cn,0,G,[],16,0,()=>V(),0,Bw,0,Q,[],1,0,0,0,B4,0,BL,[BP],1,0,()=>BE(),0,CO,0,G,[],1536,0,0,0,DA,0,G,[CO],1,0,0,0,Ec,0,G,[],16,0,0,0,Eo,0,G,[],17,0,0,0,Ek,0,G,[],17,0,0,0,Dz,0,G,[],1537,0,0,0,Cf,0,G,[Dz],1025,0,0,0,Cw,0,G,[],1537,0,0,0,CI,0,Cf,[Cw,BJ],1,0,0,0,Fb,0,Q,[],1,0,0,0,Di,0,Q,[],1,0,0,0,D9,0,G,[],17,0,0,0,B6,0,Q,[],1,0,0,0,Ff,0,G,[],1,0,0,0,BX,0,G,[],
16,0,0,0,BR,0,Q,[],1,0,0,0]);
Df([Bd,0,BR,[],1,0,0,0,Cs,0,G,[],16,0,0,0,B7,0,Bw,[],1,0,0,0,CU,0,G,[],1537,0,0,0,Ce,0,G,[CU,Cw],0,0,0,0,Ca,0,Ce,[],0,0,0,0]);
let Er=O(CD),ER=O(CP),EJ=O(DZ),Ez=O(EO),DI=O(B_),DV=O(DG),Ei=O(DM),Dr=O(Cp);
EK(["0","<java_object>@","null","String is null","String is empty","String contains invalid digits: ","String contains digits out of radix ",": ","The value is too big for long type","The value is too big for long type: ","Illegal radix: ","Either src or dest is null"]);
Y.prototype.toString=function(){return Da(this);};
Y.prototype.valueOf=Y.prototype.toString;G.prototype.toString=function(){return Da(EY(this));};
G.prototype.__teavm_class__=function(){return ES(this);};
let Fj=Symbol('jsoClass');
(()=>{let c;})();
moonChunk=C;moonLod=D;moonEntrances=E;moonHeight=F;})();