"use strict";
var moonChunk;var moonLod;var moonHeight;(function(){let Dy=2463534242,Eq=()=>{let x=Dy;x^=x<<13;x^=x>>>17;x^=x<<5;Dy=x;return x;},Bo=target=>target.$clinit=()=>{},EG=obj=>{let cls=obj.constructor;let arrayDegree=0;while(cls[H]&&cls[H].item){++arrayDegree;cls=cls[H].item;}let clsName="";if(cls[H].primitiveKind!==0){clsName=cls[H].name;}else {clsName=cls[H]?cls[H].name||"a/"+cls.name:"@"+cls.name;}while(arrayDegree-->0){clsName+="[]";}return clsName;},G=superclass=>{if(superclass===0){return function(){};}if
(superclass===void 0){superclass=BD();}return function(){superclass.call(this);};},H=Symbol("teavm_meta"),Bw=cls=>{if(cls[H].classObject===null){cls[H].classObject=Eu(cls);}return cls[H].classObject;},BD=()=>F,Cb=source=>{return Object.assign({name:null,binaryName:null,parent:null,superinterfaces:[],modifiers:0,primitiveKind:0,itemType:null,arrayType:null,enclosingClass:null,declaringClass:null,simpleName:null,clinit:()=>{},constructor:null,enumConstants:()=>null,resolvedEnumConstants:null,reflection:null,classObject
:null,assignableCache:null,valueToObject:o=>o,objectToValue:o=>o},source||{});},Bb=(name,binaryName,kind,config)=>{let cls=()=>{};let meta=Cb({name:name,binaryName:binaryName,modifiers:1|1<<4,primitiveKind:kind});cls[H]=meta;if(typeof config==='function'){config(meta);}return cls;},Ct=Bb("boolean","Z",1,meta=>{}),DP=Bb("byte","B",2,meta=>{}),EC=Bb("short","S",3,meta=>{}),CH=Bb("char","C",4,meta=>{}),B2=Bb("int","I",5,meta=>{}),EH=Bb("long","J",6,meta=>{{meta.valueToObject=o=>B_(o);}}),DC=Bb("float","F",7,meta=>
{}),Cf=Bb("double","D",8,meta=>{}),BG=(a,b)=>a===b?0:a<b? -1:1,Bg=Math.imul||function(a,b){let ah=a>>>16&0xFFFF;let al=a&0xFFFF;let bh=b>>>16&0xFFFF;let bl=b&0xFFFF;return al*bl+(ah*bl+al*bh<<16>>>0)|0;},B9=(a,b)=>(a>>>0)/(b>>>0)>>>0,EK=(a,b)=>(a>>>0)%(b>>>0)>>>0,Cv=(a,b)=>{a>>>=0;b>>>=0;return a<b? -1:a>b?1:0;},BH=BigInt(0),P=(lo,hi)=>BigInt.asIntN(64,BigInt.asUintN(64,BigInt(lo))|BigInt.asUintN(64,BigInt(hi)<<BigInt(32))),N=val=>BigInt.asIntN(64,BigInt(val|0)),DS=val=>BigInt.asIntN(64,BigInt(val>=0?Math.floor(val)
:Math.ceil(val))),EO=val=>Number(val),DO=val=>Number(BigInt.asIntN(64,val>>BigInt(32)))|0,BB=val=>Number(BigInt.asIntN(32,val))|0,CO=(a,b)=>a===b,DL=(a,b)=>a>b,D2=(a,b)=>a<b,Br=(a,b)=>BigInt.asIntN(64,a+b),ES=a=>BigInt.asIntN(64, -a),U=(a,b)=>BigInt.asIntN(64,a*b),D$=(a,b)=>BigInt.asIntN(64,a/b),CC=(a,b)=>BigInt.asIntN(64,a&b),Bd=(a,b)=>BigInt.asIntN(64,a^b),Du=(a,b)=>BigInt.asIntN(64,a<<BigInt(b&63)),BT=(a,b)=>BigInt.asIntN(64,BigInt.asUintN(64,a)>>BigInt(b&63)),X=(cls,sz)=>{let data=new Array(sz);data.fill(null);return new (M(cls))(data);},EN
=(cls,sz)=>new (M(cls))(new Array(sz)),BS=sz=>new EF(new Uint16Array(sz)),D7=sz=>new Ex(new Int8Array(sz)),Bf=sz=>new Eo(new Int16Array(sz)),C0=sz=>new Dz(new Int32Array(sz)),Ek=data=>{let buffer=new Int32Array(data.length);buffer.set(data);return new Dz(buffer);},EQ=sz=>new Ef(new Int8Array(sz)),C8=sz=>new D9(new Float32Array(sz));
let B8=sz=>new Dk(new Float64Array(sz)),Bc=data=>{let buffer=new Float64Array(data.length);buffer.set(data);return new Dk(buffer);},M=cls=>{let result=cls[H].arrayType;if(result===null){function JavaArray(data){(BD()).call(this);this.data=data;}JavaArray.prototype=Object.create((BD()).prototype);JavaArray.prototype.type=cls;JavaArray.prototype.constructor=JavaArray;JavaArray.prototype.toString=function(){let str="[";for(let i=0;i<this.data.length;++i){if(i>0){str+=", ";}str+=this.data[i].toString();}str+="]";return str;};JavaArray.prototype.cc
=function(){let dataCopy;if('slice' in this.data){dataCopy=this.data.slice();}else {dataCopy=new this.data.constructor(this.data.length);for(let i=0;i<dataCopy.length;++i){dataCopy[i]=this.data[i];}}return new (M(this.type))(dataCopy);};let name="["+cls[H].binaryName;JavaArray[H]=Cb({name:name,binaryName:name,parent:BD(),itemType:cls});result=JavaArray;cls[H].arrayType=JavaArray;}return result;},Co=(cls,dimensions)=>{let first=0;for(let i=dimensions.length -1;i>=0;i=i -1|0){if(dimensions[i]===0){first=i;break;}}if
(first>0){for(let i=0;i<first;i=i+1|0){cls=M(cls);}if(first===dimensions.length -1){return X(cls,dimensions[first]);}}let arrays=new Array(B1(dimensions,first));let firstDim=dimensions[first]|0;for(let i=0;i<arrays.length;i=i+1|0){arrays[i]=X(cls,firstDim);}return BK(cls,arrays,dimensions,first,0);},B7=dimensions=>{let arrays=new Array(B1(dimensions,0));if(arrays.length===0){return Co(Ct,dimensions);}let firstDim=dimensions[0]|0;for(let i=0;i<arrays.length;i=i+1|0){arrays[i]=EQ(firstDim);}return BK(Ct,arrays,
dimensions,0);},Eh=dimensions=>{let arrays=new Array(B1(dimensions,0));if(arrays.length===0){return Co(B2,dimensions);}let firstDim=dimensions[0]|0;for(let i=0;i<arrays.length;i=i+1|0){arrays[i]=C0(firstDim);}return BK(B2,arrays,dimensions,0);},Dd=dimensions=>{let arrays=new Array(B1(dimensions,0));if(arrays.length===0){return Co(Cf,dimensions);}let firstDim=dimensions[0]|0;for(let i=0;i<arrays.length;i=i+1|0){arrays[i]=B8(firstDim);}return BK(Cf,arrays,dimensions,0);},B1=(dimensions,start)=>{let val=dimensions[start
+1]|0;for(let i=start+2;i<dimensions.length;i=i+1|0){val=val*(dimensions[i]|0)|0;if(val===0){break;}}return val;},BK=(cls,arrays,dimensions,start)=>{let limit=arrays.length;for(let i=start+1|0;i<dimensions.length;i=i+1|0){cls=M(cls);let dim=dimensions[i];let index=0;let packedIndex=0;while(index<limit){let arr=EN(cls,dim);for(let j=0;j<dim;j=j+1|0){arr.data[j]=arrays[index];index=index+1|0;}arrays[packedIndex]=arr;packedIndex=packedIndex+1|0;}limit=packedIndex;}return arrays[0];};
function DX(array){return array.data.length;}
let Ck,Ey=strings=>{E2();Ck=new Array(strings.length);for(let i=0;i<strings.length;++i){Ck[i]=Dn(Bh(strings[i]));}},K=index=>Ck[index],Dj=(array,offset,count)=>{let result="";let limit=offset+count;for(let i=offset;i<limit;i=i+1024|0){let next=Math.min(limit,i+1024|0);result+=String.fromCharCode.apply(null,array.subarray(i,next));}return result;},Bh=str=>str===null?null:C9(str),C6=str=>str===null?null:str.bC,E2=()=>Bi(),Dn;
{Dn=str=>str;}let BM=(from,to)=>{if(from===to){return true;}let map=from[H].assignableCache;if(map===null){map=new Map();from[H].assignableCache=map;}let cachedResult=map.get(to);if(typeof cachedResult!=='undefined'){return cachedResult;}if(to[H].itemType!==null){let result=from[H].itemType!==null&&BM(from[H].itemType,to[H].itemType);map.set(to,result);return result;}let parent=from[H].parent;if(parent!==null&&parent!==from){if(BM(parent,to)){map.set(to,true);return true;}}let superinterfaces=from[H].superinterfaces;for
(let i=0;i<superinterfaces.length;i=i+1|0){if(BM(superinterfaces[i],to)){map.set(to,true);return true;}}map.set(to,false);return false;},J=ex=>{throw E3(ex);},DI=Symbol("javaException"),E3=ex=>{if(!ex.$jsException){C1(ex);}return ex.$jsException;},C1=ex=>{let javaCause=EZ(ex);let jsCause=javaCause!==null?javaCause.$jsException:void 0;let cause=typeof jsCause==="object"?{cause:jsCause}:void 0;let err=new Z("Java exception thrown",cause);if(typeof Error.captureStackTrace==="function"){Error.captureStackTrace(err);}err[DI]
=ex;ex.$jsException=err;Eg(err,ex);},Eg=(err,ex)=>{if(typeof Ea==="function"&&err.stack){let stack=Ea(err.stack);let javaStack=X(Et(),stack.length);let elem;let noStack=false;for(let i=0;i<stack.length;++i){let element=stack[i];elem=ED(Bh(element.className),Bh(element.methodName),Bh(element.fileName),element.lineNumber);if(elem==null){noStack=true;break;}javaStack.data[i]=elem;}if(!noStack){EU(ex,javaStack);}}},Z;
if(typeof Reflect==='object'){let defaultMessage=Symbol("defaultMessage");Z=function Z(message,cause){let self=Reflect.construct(Error,[void 0,cause],Z);Object.setPrototypeOf(self,Z.prototype);self[defaultMessage]=message;return self;}
;Z.prototype=Object.create(Error.prototype,{constructor:{configurable:true,writable:true,value:Z},message:{get(){try {let javaException=this[DI];if(typeof javaException==='object'){let javaMessage=DK(javaException);if(typeof javaMessage==="object"){return javaMessage!==null?javaMessage.toString():null;}}return this[defaultMessage];}catch(e){return "Exception occurred trying to extract Java exception message: "+e;}}}});}else {Z=Error;}let DK=t=>EW(t),EZ=t=>E1(t),Et=()=>BD(),ED=(className,methodName,fileName,
lineNumber)=>{{return null;}},EU=(e,stack)=>{},C2=null,DM=data=>{let i=0;let packages=new Array(data.length);for(let j=0;j<data.length;++j){let prefixIndex=data[i++];let prefix=prefixIndex>=0?packages[prefixIndex]:"";packages[j]=prefix+data[i++]+".";}C2=packages;},EB=[],C_=data=>{let packages=C2;let i=0;while(i<data.length){let cls=data[i++];EB.push(cls);let m=Cb();cls[H]=m;let className=data[i++];m.name=className!==0?className:null;if(m.name!==null){let packageIndex=data[i++];if(packageIndex>=0){m.name=packages[packageIndex]
+m.name;}}m.binaryName="L"+m.name+";";let superclass=data[i++];m.parent=superclass!==0?superclass:null;m.superinterfaces=data[i++];if(m.parent){cls.prototype=Object.create(m.parent.prototype);}else {cls.prototype={};}cls.prototype.constructor=cls;m.modifiers=data[i++];m.primitiveKind=0;let innerClassInfo=data[i++];if(innerClassInfo!==0){let enclosingClass=innerClassInfo[0];m.enclosingClass=enclosingClass!==0?enclosingClass:null;let declaringClass=innerClassInfo[1];m.declaringClass=declaringClass!==0?declaringClass
:null;let simpleName=innerClassInfo[2];m.simpleName=simpleName!==0?simpleName:null;}let clinit=data[i++];m.clinit=clinit!==0?()=>{m.clinit=()=>{};clinit();}:()=>{};let virtualMethods=data[i++];if(virtualMethods!==0){for(let j=0;j<virtualMethods.length;j+=2){let name=virtualMethods[j];let func=virtualMethods[j+1];if(typeof name==='string'){name=[name];}for(let k=0;k<name.length;++k){cls.prototype[name[k]]=func;}}}}};
function F(){this.$id$=0;}
let BO=a=>{return Bw(Ee(a));},Ee=a=>{return a.constructor;},EM=a=>{let b,c,d,e,f,g,h,i,j,k;b=a;if(!b.$id$)b.$id$=Eq();c=a.$id$;Cy();if(!c)d=K(0);else{if(!c)e=32;else{f=0;e=c>>>16|0;if(e)f=16;else e=c;g=e>>>8|0;if(!g)g=e;else f=f|8;h=g>>>4|0;if(!h)h=g;else f=f|4;e=h>>>2|0;if(!e)e=h;else f=f|2;if(e>>>1|0)f=f|1;e=(32-f|0)-1|0;}i=(((32-e|0)+4|0)-1|0)/4|0;j=BS(i);k=j.data;i=(i-1|0)*4|0;e=0;while(i>=0){h=e+1|0;k[e]=Cc((c>>>i|0)&15,16);i=i-4|0;e=h;}d=D6(j);}b=Bz();T(T(b,K(1)),d);return BE(b);},By=G(0),BF=G(0),Cg=G(0),S
=G(),DU=null,Dw=null,Er=null,Bi=()=>{Bi=Bo(S);Ew();},DT=(a,b)=>{Bi();a.bC=Dj(b.data,0,b.data.length);},D6=a=>{let b=new S();DT(b,a);return b;},En=(a,b)=>{a.bC=b;},C9=a=>{let b=new S();En(b,a);return b;},Cs=(a,b)=>{let c;if(b>=0&&b<a.bC.length)return a.bC.charCodeAt(b);c=new BY;O(c);J(c);},Ci=(a,b,c)=>{let d,e,f;d=a.bC.length;e=BG(b,c);if(!e)a=Dw;else if(!(!b&&c==d)){if(b>=0&&e<=0&&c<=d)a=C9(a.bC.substring(b,c));else{f=new BY;O(f);J(f);}}return a;},Cn=b=>{Bi();return b===null?K(2):b;},Ew=()=>{let b;DU=BS(0);b
=new S;Bi();b.bC="";Dw=b;Er=new DE;},BA=G(),Do=G(BA),EA=null,Cy=()=>{Cy=Bo(Do);Ep();},Ep=()=>{EA=Bw(B2);};
function Cj(){let a=this;F.call(a);a.bD=null;a.bE=0;}
let Ce=(a,b,c)=>{let d,e,f,g;d=a.bE;e=d-b|0;d=(d+c|0)-b|0;Dh(a,d);f=e-1|0;while(f>=0){g=a.bD.data;g[c+f|0]=g[b+f|0];f=f+(-1)|0;}a.bE=a.bE+(c-b|0)|0;},DH=G(0),Dg=G(Cj),EL=a=>{a.bD=BS(16);},Bz=()=>{let a=new Dg();EL(a);return a;},T=(a,b)=>{let c,d,e,f,g,h;c=a.bE;d=a;b=b===null?K(2):b;e=d;if(c>=0&&c<=e.bE){a:{if(b===null)b=K(2);else if(b.bC.length?0:1)break a;f=e.bE+b.bC.length|0;Dh(e,f);f=e.bE-1|0;while(f>=c){e.bD.data[f+b.bC.length|0]=e.bD.data[f];f=f+(-1)|0;}e.bE=e.bE+b.bC.length|0;f=0;while(f<b.bC.length){g
=e.bD.data;h=c+1|0;g[c]=Cs(b,f);f=f+1|0;c=h;}}return a;}b=new BY;DF(b);J(b);},CN=(a,b)=>{let c,d,e,f,g,h,i,j;c=a.bE;d=1;if(b<0){d=0;b= -b|0;}a:{if(Cv(b,10)<0){if(d)Ce(a,c,c+1|0);else{Ce(a,c,c+2|0);e=a.bD.data;f=c+1|0;e[c]=45;c=f;}a.bD.data[c]=Cc(b,10);}else{g=1;h=1;f=B9((-1),10);b:{while(true){i=g*10|0;if(Cv(i,b)>0){i=g;break b;}h=h+1|0;if(Cv(i,f)>0)break;g=i;}}if(!d)h=h+1|0;Ce(a,c,c+h|0);if(d)f=c;else{e=a.bD.data;f=c+1|0;e[c]=45;}while(true){if(!i)break a;e=a.bD.data;j=f+1|0;e[f]=Cc(B9(b,i),10);b=EK(b,i);i
=B9(i,10);f=j;}}}return a;},BE=a=>{let b,c,d,e,f;b=new S;c=a.bD;d=c.data;e=a.bE;Bi();f=d.length;if(e>=0&&e<=(f-0|0)){b.bC=Dj(c.data,0,e);return b;}b=new Bl;O(b);J(b);},Dh=(a,b)=>{let c,d,e,f;c=a.bD.data.length;if(c<b){b=c>=1073741823?2147483647:Bq(b,Bq(c*2|0,5));d=a.bD.data;e=BS(b);f=e.data;b=Ca(b,d.length);c=0;while(c<b){f[c]=d[c];c=c+1|0;}a.bD=e;}};
function B6(){let a=this;F.call(a);a.b6=null;a.cb=null;a.b9=0;a.b7=0;}
let E_=a=>{return a;},Da=a=>{C1(a);},EW=a=>{return a.b6;},E1=a=>{let b;b=a.cb;if(b===a)b=null;return b;},Cu=G(B6),L=G(Cu),O=a=>{Da(a);a.b9=1;a.b7=1;},E7=()=>{let a=new L();O(a);return a;},V=(a,b)=>{Da(a);a.b9=1;a.b7=1;a.b6=b;},E8=a=>{let b=new L();V(b,a);return b;},Bx=G(),D1=G(Bx),DJ=G(Bx),CA=G(0),Dq=G(0),CZ=G(0);
function CX(){F.call(this);this.bI=null;}
let Eu=b=>{let c;c=new CX;c.bI=b;return c;},BW=a=>{return !a.bI[H].primitiveKind?0:1;},Db=a=>{let b;b=a.bI[H].itemType;return b===null?null:Bw(b);},DA=G(),CE=null,CR=BH,B$=null,Ba=()=>{Ba=Bo(DA);DV();},Cw=b=>{let c,d,e;Ba();a:{if(B$!==null){c=CE;if(b===c)d=1;else if(!(c instanceof S))d=0;else{c=c;d=b.bC!==c.bC?0:1;}if(d)break a;}CE=b;Bs();if(b===null){b=new W;V(b,K(3));J(b);}e=DN(b,0,b.bC.length,10);CR=e;b=new Cd;R();c=new Cz;d=C7(16);c.bK=0;c.bF=X(B3,d);c.b_=0.75;CI(c);b.bQ=c;b.b5=e;B$=b;}return B$;},BR=b=>
{let c,d,e,f;Ba();b=b.data;c=b.length;d=new Int16Array(c);e=0;while(e<c){f=b[e];d[e]=f;e=e+1|0;}return d;},DG=b=>{let c,d,e,f;Ba();b=b.data;c=b.length;d=new Float32Array(c);e=0;while(e<c){f=b[e];d[e]=f;e=e+1|0;}return d;},EP=(b,c,d,e)=>{return {tops:b,mats:c,ring:d,runs:e};},DQ=(b,c)=>{return {h:b,m:c};},C=(b,c,d)=>{let e,f;Ba();b=Bh(b);e=c;f=d;b=D8(Cw(b),CR,e,f);return EP(BR(b.bU),BR(b.b0),BR(b.bJ),BR(b.bZ));},D=(b,c,d,e,f)=>{let g,h,i,j,k,l,m,n,o,p,q,r,s;Ba();b=Bh(b);g=c;h=d;i=e;j=f;b=Cw(b);k=i+1|0;i=Bg(k,
k);l=C8(i);m=l.data;n=C8(i);o=n.data;p=0;while(p<k){q=0;while(q<k){i=g+Bg(q,j)|0;r=h+Bg(p,j)|0;s=Bg(p,k)+q|0;m[s]=Bv(b,i,r);o[s]=Cq(b,i,r);q=q+1|0;}p=p+1|0;}m=X(M(DC),2).data;m[0]=l;m[1]=n;return DQ(DG(m[0]),DG(m[1]));},E=(b,c,d)=>{let e,f;Ba();b=Bh(b);e=c;f=d;return Bv(Cw(b),e,f);},DV=()=>{return;},EI=G(),Ei=G(),EV=G(),Dx=G(0),DE=G(),Cp=G(),Ez=null,ET=null,Cm=()=>{Cm=Bo(Cp);Eb();},Cc=(b,c)=>{Cm();if(c>=2&&c<=36&&b>=0&&b<c)return b<10?(48+b|0)&65535:((97+b|0)-10|0)&65535;return 0;},Eb=()=>{Ez=Bw(CH);ET=X(Cp,
128);},DR=G(),Ev=G(),DW=G(),D8=(b,c,d,e)=>{let f,g,h,i,j,k,l,m,n,o,p,q,r,s,t;f=d*16|0;g=e*16|0;h=D7(65536);i=h.data;j=0;while(j<256){d=j?Dm(j):1;a:{k=d<<24>>24;if(k){l=0;while(true){if(l>=256)break a;i[(j*256|0)+l|0]=k;l=l+1|0;}}}j=j+1|0;}m=new Ds;m.b3=h;m.b2=g;m.b4=f;Es(b,c,f,g,m);m=new De;m.bU=Bf(256);m.b0=Bf(256);m.bJ=Bf(64);m.bZ=Bf(0);n=0;o=Bf(3072);l=0;while(l<256){j=255;while(j>0&&!i[(j*256|0)+l|0]){j=j+(-1)|0;}k=i[(j*256|0)+l|0];h=m.bU;d=k!=4&&k!=5?(2*j|0)+2|0:(2*j|0)+1|0;h.data[l]=d<<16>>16;m.b0.data[l]
=k<<16>>16;p=(-1);q=4;while(true){d=BG(q,j);if(d>0)break;r=d<0&&!i[(q*256|0)+l|0]?1:0;if(r&&p<0)p=q;if(!r&&p>=0){h=o.data;d=n+1|0;e=d*3|0;k=h.length;if(e>k){s=Bf(k*2|0);C4(o,0,s,0,k);o=s;}h=o.data;e=n*3|0;h[e]=l<<16>>16;h[e+1|0]=p<<16>>16;h[e+2|0]=(q-1|0)<<16>>16;p=(-1);n=d;}q=q+1|0;}l=l+1|0;}d=n*3|0;i=Bf(d);m.bZ=i;C4(o,0,i,0,d);t=0;p=f-1|0;e=f+16|0;k=g-1|0;n=g+16|0;while(t<16){i=m.bJ.data;j=g+t|0;i[t]=BZ(b,p,j)<<16>>16;m.bJ.data[16+t|0]=BZ(b,e,j)<<16>>16;i=m.bJ.data;d=32+t|0;j=f+t|0;i[d]=BZ(b,j,k)<<16>>16;m.bJ.data[48
+t|0]=BZ(b,j,n)<<16>>16;t=t+1|0;}return m;},BZ=(b,c,d)=>{let e,f,g,h,i,j,k;e=Bv(b,c,d);f=Bt(e)|0;g=!(e-f>=0.5)?0:1;h=f-1|0;i=Dl();j=Di(b,c,d,i);if(j&&CL(i,h))g=0;if(g)return (2*f|0)+1|0;k=h;while(j&&k>=4&&CP(i,k,h)){k=k+(-1)|0;}return (2*k|0)+2|0;};
function De(){let a=this;F.call(a);a.bU=null;a.b0=null;a.bJ=null;a.bZ=null;}
function Cd(){let a=this;F.call(a);a.b5=BH;a.bQ=null;}
let CJ=null,CK=null,Bm=null,CS=null,CB=null,CQ=null,C$=null,Dp=null,CY=null,C5=null,CV=0,Bk=null,R=()=>{R=Bo(Cd);Ej();},BC=b=>{R();b=U(Bd(b,BT(b,30)),P(484763065, 3210233709));b=U(Bd(b,BT(b,27)),P(321982955, 2496678331));return Bd(b,BT(b,31));},I=(b,c)=>{R();return EO(BT(BC(Br(b,U(N(c),P(2135587861, 2654435769)))),11))*1.1102230246251565E-16;},Bj=(a,b,c,d)=>{return BC(Bd(Bd(a.b5,BC(U(N(b),P(3652509721, 1663821211)))),BC(Br(U(N(c),P(2135587861, 2654435769)),U(N(d),P(668265295, 3266489917))))));},Df=b=>{R();return b
*b*b*(b*(b*6.0-15.0)+10.0);},Dv=(a,b,c,d)=>{let e,f,g,h,i,j,k,l,m,n,o;e=Bt(b)|0;f=Bt(c)|0;g=Df(b-e);h=Df(c-f);i=I(Bj(a,d,e,f),0);j=e+1|0;k=I(Bj(a,d,j,f),0);l=f+1|0;m=I(Bj(a,d,e,l),0);n=I(Bj(a,d,j,l),0);o=i+(k-i)*g;return (o+(m+(n-m)*g-o)*h)*2.0-1.0;},Q=(a,b,c,d,e)=>{let f,g,h,i;f=0.0;g=1.0;h=0.0;i=0;while(i<d){f=f+Dv(a,b,c,e+(i*31|0)|0)*g;h=h+g;b=b*2.03;c=c*2.03;g=g*0.5;i=i+1|0;}return f/h;},BL=(b,c,d)=>{let e;R();e=Y(0.0,BI(1.0,(d-b)/(c-b)));return e*e*(3.0-2.0*e);},Cq=(a,b,c)=>{return BL(0.0,0.22, -Q(a,b/
650.0,c/650.0,3,1));},Bv=(a,b,c)=>{let d,e,f,g,h,i,j,k,l,m,n,o;d=Cq(a,b,c);e=1.0-d;f=b;g=f/900.0;h=c;i=64.0+Q(a,g,h/900.0,3,2)*9.0-d*5.0+Q(a,f/70.0,h/70.0,4,3)*(2.5+7.5*e);g=f/280.0;j=h/280.0;k=0.0;l=1.0;m=0.0;n=0;while(n<4){o=1.0-Cr(Dv(a,g,j,4+(n*17|0)|0));k=k+o*o*l;m=m+l;g=g*2.1;j=j*2.1;l=l*0.5;n=n+1|0;}return Y(8.0,BI(225.0,i+DD(Y(0.0,k/m-0.55)/0.45,1.5)*60.0*e+(1.0-Cr(Q(a,f/130.0,h/130.0,2,5)))*2.2*d+E4(a,b,c,d)+Q(a,f/9.0,h/9.0,2,6)*0.9));},E4=(a,b,c,d)=>{let e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,
ba,bb,bc,bd,be,bf,bg;e=0.0;f=0;g=1.0-0.55*d;h=b;i=c;while(true){R();j=CJ.data;if(f>=j.length)break;k=j[f];l=Bp(b,k);m=Bp(c,k);n=(-1);o=k;while(n<=1){p=(-1);while(p<=1){q=l+n|0;r=m+p|0;s=Bj(a,100+f|0,q,r);if(!(I(s,0)>CK.data[f])){t=(q+I(s,1))*o;u=(r+I(s,2))*o;v=o*(0.1+0.12*I(s,3));w=h-t;x=i-u;y=w*w+x*x;z=v*2.6;if(!(y>z*z)){ba=D0(x,w);bb=1.0+0.07*CD(3.0*ba+I(s,5)*6.28)+0.04*CD(5.0*ba+I(s,6)*6.28);bc=Be(y)/(v*bb);bd=I(s,4);be=BI(38.0,0.3*v+0.8)*(1.0-0.55*bd);bf=BI(24.0,0.09*v+0.4)*(1.0-0.6*bd);bg=f<2?1.0:g;k=!(v
>=30.0)?0:1;t=0.0;if(bc<1.0)t=t-be*(1.0-bc*bc);d=(bc-1.0)/0.17;d=t+bf*CU( -d*d);bd=Y(bc,1.0);d=d+0.4*bf*DD(bd,(-3.0))*(1.0-BL(1.4,2.6,bc));if(k){bd=0.5*be;be=bc/0.13;d=d+bd*CU( -be*be);}e=e+d*bg;}}p=p+1|0;}n=n+1|0;}f=f+1|0;}return e;},Dl=()=>{let b,c,d,e,f;R();b=X(Ch,Bm.data.length+1|0);c=b.data;d=0;e=c.length;while(d<e){f=new Ch;f.bG=2147483647;f.bH=(-2147483648);c[d]=f;d=d+1|0;}return b;},CL=(b,c)=>{let d,e,f;R();b=b.data;d=b.length;e=0;while(e<d){f=b[e];if(f.bH==1000&&c>=f.bG)return 1;e=e+1|0;}return 0;},Bn
=(a,b,c,d)=>{return Q(a,b/150.0,c/150.0,2,(20+(d<4?0:200)|0)+d|0);},CW=(a,b,c,d,e)=>{let f,g,h,i,j,k,l,m,n,o;f=d<4?0:200;g=b;h=g/210.0;i=c;j=Q(a,h,i/210.0,2,(40+f|0)+d|0);k=BL(CQ.data[d],C$.data[d],j);if(k<=0.0)return 0;l=Bn(a,g,i,d);m=Bn(a,b+2|0,i,d)-l;n=Bn(a,g,c+2|0,d)-l;h=Be(m*m+n*n)/2.0;if(h<0.0015)return 0;o=e.data;o[0]=Cr(l)/h;o[1]=(Dp.data[d]+CY.data[d]*I(Bj(a,(50+f|0)+d|0,Bp(b,160),Bp(c,160)),0))*k*C5.data[d];n=Bm.data[d];e=CB.data;o[2]=n+Q(a,g/e[d],i/e[d],d!=2&&d!=3?1:2,(60+f|0)+d|0)*CS.data[d];return 1;},D4
=(a,b,c)=>{let d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v;d=Bj(a,400,b,c);if(I(d,0)>=0.4)return Bk;e=(b+0.12+0.76*I(d,1))*224.0;f=(c+0.12+0.76*I(d,2))*224.0;g=Ca(Bm.data.length-1|0,I(d,3)*Bm.data.length|0);h=0;i=e;j=f;a:{while(true){if(h>=10)break a;k=Bn(a,i,j,g);l=(Bn(a,i+2.0,j,g)-k)/2.0;m=(Bn(a,i,j+2.0,g)-k)/2.0;n=l*l+m*m;if(n<1.0E-9)break;o=k*l/n;p=k*m/n;q=Be(o*o+p*p);if(q<0.3)break a;if(q>30.0){q=30.0/q;o=o*q;p=p*q;}i=i-o;j=j-p;h=h+1|0;}return Bk;}if(BV(i-e,j-f)>70.0)return Bk;r=BB((BQ(i)));s=BB((BQ(j)));t=B8(3);if
(CW(a,r,s,g,t)){t=t.data;if(!(t[1]<2.6)&&!(t[0]>t[1]*0.6)){i=Bv(a,r,s);u=Y(0.0,i-11.0-2.0*I(d,4)-t[2]);if(!(u>45.0)&&!(i-(t[2]+u)<5.0)){v=new BP;v.bO=r;v.bN=s;v.b1=g;v.b8=u;v.ca=t[2]+u;v.bY=Y(50.0,u*2.2);e=t[1]+1.5+1.5*I(d,5);v.b$=e;v.bT=e+45.0;return v;}return Bk;}}return Bk;},El=(a,b,c,d,e,f)=>{let g,h,i,j,k,l,m;if(!CW(a,b,c,d,e))return 0;g=f.data;h=g.length;i=0;while(i<h){j=g[i];if(j!==null&&j.b1==d){k=BV(b-j.bO|0,c-j.bN|0);l=j.bY;if(k<l){f=e.data;m=BL(0.0,1.0,1.0-k/l);f[2]=f[2]+j.b8*m;f[1]=f[1]*(1.0+0.5
*m);}}i=i+1|0;}e=e.data;return e[0]<e[1]&&e[1]>=1.2?1:0;},Di=(a,b,c,d)=>{let e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ba,bb,bc,bd,be,bf,bg;e=0;f=B8(3);g=X(BP,9);h=g.data;i=0;j=Bp(b,224);k=Bp(c,224);l=(-1);while(l<=1){m=(-1);while(m<=1){n=j+l|0;o=k+m|0;p=Bd(Du(N(n),32),CC(N(o),P(4294967295, 0)));q=a.bQ;r=B_(p);if(r===null)q=Dt(q);else{s=CT(r);q=CF(q,r,s&(q.bF.data.length-1|0),s);}t=q===null?null:q.bS;if(t===null){t=D4(a,n,o);q=a.bQ;r=B_(p);if(r===null){u=Dt(q);if(u===null){q.bM=q.bM+1|0;u=DB(q,null,0,0);v
=q.bK+1|0;q.bK=v;if(v>q.bW)C3(q);}}else{s=CT(r);v=s&(q.bF.data.length-1|0);u=CF(q,r,v,s);if(u===null){q.bM=q.bM+1|0;u=DB(q,r,v,s);v=q.bK+1|0;q.bK=v;if(v>q.bW)C3(q);}}u.bS=t;}R();if(t!==Bk&&BV(b-t.bO|0,c-t.bN|0)<Y(t.bY,t.bT)){v=i+1|0;h[i]=t;i=v;}m=m+1|0;}l=l+1|0;}w=f.data;k=0;while(true){R();if(k>=Bm.data.length)break;r=d.data[k];r.bG=2147483647;r.bH=(-2147483648);r.bV=0;if(El(a,b,c,k,f,g)){x=w[0]/w[1];y=w[1]*0.65*Be(Y(0.0,1.0-x*x));if(!(y<0.8)){r.bG=Bq(4,EY(w[2]-y)|0);r.bH=Bt(w[2]+y)|0;e=1;}}k=k+1|0;}u=d.data[CV];u.bG
=2147483647;u.bH=(-2147483648);u.bV=0;z=1.7976931348623157E308;i=h.length;j=0;y=b;ba=y/20.0;bb=c;bc=bb/20.0;bd=y/7.0;be=bb/7.0;x=y/4.0;bb=bb/4.0;while(j<i){q=h[j];if(q!==null){bf=BV(b-q.bO|0,c-q.bN|0);if(!(bf>q.bT)){bg=Y(0.0,bf+Q(a,ba,bc,1,412)*5.5+Q(a,bd,be,2,410)*1.8-q.b$);y=bg<=2.5?bg*3.5:8.75+(bg-2.5)*1.6;z=BI(z,q.ca-2.0+y+Q(a,x,bb,1,411)*1.2);}}j=j+1|0;}if(z<160.0){u.bG=Bq(4,Bt(z)|0);u.bH=1000;e=1;}return e;},Ej=()=>{let b,c;CJ=Ek([20,44,96,208,448,960]);CK=Bc([0.85,0.7,0.55,0.45,0.4,0.35]);b=C0(6);c=b.data;c[0]
=30;c[1]=43;c[2]=38;c[3]=38;c[4]=19;c[5]=8;Bm=b;CS=Bc([11.0,7.0,20.0,20.0,9.0,6.0]);CB=Bc([70.0,70.0,140.0,140.0,80.0,80.0]);CQ=Bc([0.05,0.05,0.2,0.2,0.05,0.05]);C$=Bc([0.32,0.32,0.47,0.47,0.32,0.32]);Dp=Bc([3.0,3.0,2.4,2.4,3.0,3.0]);CY=Bc([3.5,3.5,2.6,2.6,3.5,3.5]);C5=Bc([1.0,1.0,1.0,1.0,1.25,1.45]);CV=c.length;Bk=new BP;},Bl=G(L),DF=a=>{O(a);},E$=()=>{let a=new Bl();DF(a);return a;};
function BU(){BA.call(this);this.bP=BH;}
let DZ=null,Bs=()=>{Bs=Bo(BU);EJ();},B_=b=>{let c;Bs();c=new BU;c.bP=b;return c;},DN=(b,c,d,e)=>{let f,g,h,i,j,k,l,m;Bs();if(e>=2&&e<=36){if(c==d){b=new W;V(b,K(4));J(b);}a:{f=0;b=b;switch(Cs(b,c)){case 43:g=c+1|0;break a;case 45:f=1;g=c+1|0;break a;default:}g=c;}h=BH;i=N(e);j=Br(N(1),D$(P(4294967295, 2147483647),i));if(g==d){b=new W;O(b);J(b);}while(g<d){k=g+1|0;g=Cs(b,g);g=g>=48&&g<=57?g-48|0:g>=97&&g<=122?(g-97|0)+10|0:g>=65&&g<=90?(g-65|0)+10|0:(-1);if(g<0){l=new W;b=Cn(Ci(b,c,d));m=Bz();T(T(m,K(5)),b);V(l,
BE(m));J(l);}if(g>=e){l=new W;b=Cn(Ci(b,c,d));m=Bz();T(T(CN(T(m,K(6)),e),K(7)),b);V(l,BE(m));J(l);}if(DL(h,j)){b=new W;V(b,K(8));J(b);}h=Br(U(i,h),N(g));if(D2(h,BH)){if(k==d&&CO(h,P(0, 2147483648))&&f)return P(0, 2147483648);l=new W;b=Cn(Ci(b,c,d));m=Bz();T(T(m,K(9)),b);V(l,BE(m));J(l);}g=k;}if(f)h=ES(h);return h;}b=new W;l=Bz();CN(T(l,K(10)),e);V(b,BE(l));J(b);},CT=a=>{let b;b=a.bP;Bs();return BB(b)^DO(b);},EJ=()=>{DZ=Bw(EH);},CG=G(0);
function Ds(){let a=this;F.call(a);a.b3=null;a.b2=0;a.b4=0;}
let Cx=(a,b,c,d,e)=>{let f,g,h;f=a.b3;g=a.b2;h=a.b4;if(c>=0&&c<256)f.data[((c*256|0)+((d-g|0)*16|0)|0)+(b-h|0)|0]=e<<24>>24;},D3=G(),Dm=b=>{if(b<=59)return 1;return b>=64?0:2;},Es=(b,c,d,e,f)=>{let g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ba,bb,bc,bd,be,bf,bg,bh,bi,bj,bk,bl,bm,bn;g=Dd([18,18]).data;h=0;while(h<18){i=0;while(i<18){g[h].data[i]=Bv(b,(d+h|0)-1|0,(e+i|0)-1|0);i=i+1|0;}h=h+1|0;}j=Eh([16,16]);k=j.data;l=Dd([16,16]);m=l.data;n=B7([16,16]);o=n.data;p=B7([16,16]);q=p.data;r=Dl();s=0;while(s<16){t=0;while
(t<16){u=d+s|0;v=e+t|0;w=s+1|0;x=g[w].data;y=t+1|0;z=x[y];ba=Bt(z)|0;bb=!(z-ba>=0.5)?0:1;bc=ba-1|0;bd=(g[s+2|0].data[y]-g[s].data[y])/2.0;be=(g[w].data[t+2|0]-g[w].data[t])/2.0;bf=Be(bd*bd+be*be);m[s].data[t]=bf;w=!(Cq(b,u,v)>0.5)?0:1;bg=bf>0.85?0:Bq(1,Ca(4,BB((BQ(3.4-bf*3.2+(Bu(c,u,v,0)-0.5)*1.2)))));bh=Di(b,u,v,r);bi=bh&&CL(r,bc)?1:0;o[s].data[t]=bi;if(bi)bb=0;bj=bg<=0?4:5;bk=Bq(ba+1|0,64);bl=1;while(bl<=bk){h=BG(bl,ba);if(h>0)bm=0;else if(!h)bm=!bb?0:bj;else{bn=bc-bl|0;bm=bn<bg?2:w&&bn<(bg+4|0)?3:1;if(bh
&&CP(r,bl,bc))bm=0;}if(bm!=Dm(bl))Cx(f,u,bl,v,bm);bl=bl+1|0;}k[s].data[t]=bc;q[s].data[t]=bb;t=y;}s=s+1|0;}ER(b,c,d,e,j,l,n,p,f);},CP=(b,c,d)=>{let e,f,g,h,i;b=b.data;e=b.length;f=0;g=BG(c,4);d=BG(c,d);while(f<e){h=b[f];i=h.bH;if(i!=(-2147483648)&&g>=0){if(c>=h.bG&&c<=i)return 1;if(h.bV&&c>i&&d<=0)return 1;}f=f+1|0;}return 0;},ER=(b,c,d,e,f,g,h,i,j)=>{let k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ba;k=B7([16,16]).data;l=1;while(l<15){m=1;while(m<15){a:{n=h.data;o=d+l|0;p=e+m|0;if(!n[l].data[m]&&!k[l].data[m]&&!(g.data[l].data[m]
>0.9)){q=!(Q(b,o/45.0,p/45.0,1,90)>0.25)?0.0025:0.035;if(!(Bu(c,o,p,1)>=q)){r=Bu(c,o,p,2)<0.25&&l>=2&&l<=13&&m>=2&&m<=13?2:1;s= -r|0;t=s;while(true){if(t>r)break a;u=s;while(u<=r){v=Be(Bg(t,t)+Bg(u,u)|0);q=r;if(!(v>q+0.4)){w=l+t|0;x=m+u|0;if(!n[w].data[x]){v=q+0.8-v;o=d+w|0;p=e+x|0;y=BB((BQ(v*(0.8+Bu(c,o,p,3)*0.6))));z=0;while(z<y){ba=(f.data[w].data[x]+1|0)+z|0;Cx(j,o,ba,p,1);z=z+1|0;}k[w].data[x]=1;}}u=u+1|0;}t=t+1|0;}}}}m=m+1|0;}l=l+1|0;}s=0;while(s<16){ba=0;while(ba<16){if(!k[s].data[ba]&&!h.data[s].data[ba]
&&!i.data[s].data[ba]&&!(g.data[s].data[ba]>0.6)){m=d+s|0;w=e+ba|0;if(Bu(c,m,w,4)<0.02){x=f.data[s].data[ba]+1|0;Cx(j,m,x,w,4);}}ba=ba+1|0;}s=s+1|0;}},Bu=(b,c,d,e)=>{return I(BC(Br(Br(U(b,N(31)),Bd(Du(N(c),32),CC(N(d),P(4294967295, 0)))),U(N(e),P(2135587861, 2654435769)))),0);},Ec=G(),E6=(b,c,d,e,f)=>{let g,h,i,j,k,l,m,n;if(b!==null&&d!==null){if(c>=0&&e>=0&&f>=0&&(c+f|0)<=B0(b)&&(e+f|0)<=B0(d)){a:{b:{if(b!==d){g=Db(BO(b));h=Db(BO(d));if(g!==null&&h!==null){if(g===h)break b;if(!BW(g)&&!BW(h)){i=b;j=0;k=c;while
(j<f){c:{l=i.data;m=k+1|0;n=l[k];if(n!==null){n=BO(n);if(BM(n.bI,h.bI)){k=1;break c;}}k=0;}if(!k){BN(b,c,d,e,j);b=new BX;O(b);J(b);}j=j+1|0;k=m;}BN(b,c,d,e,f);return;}if(!BW(g))break a;if(BW(h))break b;else break a;}b=new BX;O(b);J(b);}}BN(b,c,d,e,f);return;}b=new BX;O(b);J(b);}b=new Bl;O(b);J(b);}d=new Dc;V(d,K(11));J(d);},C4=(b,c,d,e,f)=>{if(c>=0&&e>=0&&f>=0&&(c+f|0)<=B0(b)&&(e+f|0)<=B0(d)){BN(b,c,d,e,f);return;}b=new Bl;O(b);J(b);},BN=(b,c,d,e,f)=>{if(f!==0){if(typeof b.data.buffer!=='undefined'){d.data.set(b.data.subarray(c,
c+f),e);}else if(b!==d||e<c){for(let i=0;i<f;i=i+1|0){d.data[e++]=b.data[c++];}}else {c=c+f|0;e=e+f|0;for(let i=0;i<f;i=i+1|0){d.data[ --e]=b.data[ --c];}}}},D_=G(),CD=b=>{return Math.sin(b);},CU=b=>{return Math.exp(b);},Be=b=>{return Math.sqrt(b);},EY=b=>{return Math.ceil(b);},Bt=b=>{return Math.floor(b);},DD=(b,c)=>{return Em(b,c);},Em=(b,c)=>{return Math.pow(b,c);},D0=(b,c)=>{return Math.atan2(b,c);},BQ=b=>{return DS(b+D5(b)*0.5);},Bp=(b,c)=>{let d;d=b/c|0;if((b^c)<0&&Bg(d,c)!=b)d=d-1|0;return d;},Ca=(b,
c)=>{if(b<c)c=b;return c;},Bq=(b,c)=>{if(b>c)c=b;return c;},EX=(b,c)=>{return Math.min(b,c);},BI=(b,c)=>{return EX(b,c);},Ed=(b,c)=>{return Math.max(b,c);},Y=(b,c)=>{return Ed(b,c);},EE=b=>{return Math.abs(b);},Cr=b=>{return EE(b);},D5=b=>{return Math.sign(b);},BV=(b,c)=>{return Be(b*b+c*c);},Dr=G(0),B5=G(),Cl=G(0);
function Cz(){let a=this;B5.call(a);a.bK=0;a.bF=null;a.bM=0;a.b_=0.0;a.bW=0;}
let C7=b=>{let c;if(b>=1073741824)return 1073741824;if(!b)return 16;c=b-1|0;b=c|c>>1;b=b|b>>2;b=b|b>>4;b=b|b>>8;return (b|b>>16)+1|0;},CI=a=>{a.bW=a.bF.data.length*a.b_|0;},CF=(a,b,c,d)=>{let e,f,g;e=a.bF.data[c];while(e!==null){if(e.bR==d){a:{f=e.bX;if(b!==f){g=b;if(!(g===f?1:f instanceof BU&&CO(f.bP,g.bP)?1:0)){c=0;break a;}}c=1;}if(c)break;}e=e.bL;}return e;},Dt=a=>{let b;b=a.bF.data[0];while(b!==null&&b.bX!==null){b=b.bL;}return b;},DB=(a,b,c,d)=>{let e,f,g;e=new B3;f=null;e.bX=b;e.bS=f;e.bR=d;g=a.bF.data;e.bL
=g[c];g[c]=e;return e;},C3=a=>{let b,c,d,e,f,g,h,i;b=a.bF.data.length;b=C7(!b?1:b<<1);c=X(B3,b);d=c.data;e=0;f=b-1|0;while(true){g=a.bF.data;if(e>=g.length)break;h=g[e];g[e]=null;while(h!==null){b=h.bR&f;i=h.bL;h.bL=d[b];d[b]=h;h=i;}e=e+1|0;}a.bF=c;CI(a);},E0=G(L),Dc=G(L),DY=G(),B0=b=>{let c;c=(BO(b)).bI;if(c[H].itemType!==null)return DX(b);b=new BJ;O(b);J(b);},BX=G(L);
function BP(){let a=this;F.call(a);a.bO=0;a.bN=0;a.b1=0;a.ca=0.0;a.b8=0.0;a.bY=0.0;a.b$=0.0;a.bT=0.0;}
let BJ=G(L),W=G(BJ);
function Ch(){let a=this;F.call(a);a.bG=0;a.bH=0;a.bV=0;}
let BY=G(Bl),CM=G(0);
function B4(){let a=this;F.call(a);a.bX=null;a.bS=null;}
function B3(){let a=this;B4.call(a);a.bR=0;a.bL=null;}
let E5=G();
DM([]);
C_([F,0,0,[],1,0,0,0,By,0,F,[],1537,0,0,0,BF,0,F,[],1537,0,0,0,Cg,0,F,[],1537,0,0,0,S,0,F,[By,BF,Cg],17,0,()=>Bi(),0,BA,0,F,[By],1025,0,0,0,Do,0,BA,[BF],1,0,()=>Cy(),0,Cj,0,F,[By,Cg],0,0,0,0,DH,0,F,[],1537,0,0,0,Dg,0,Cj,[DH],1,0,0,0,B6,0,F,[],1,0,0,0,Cu,0,B6,[],1,0,0,0,L,0,Cu,[],1,0,0,0,Bx,0,F,[],1025,0,0,0,D1,0,Bx,[],17,0,0,0,DJ,0,Bx,[],17,0,0,0,CA,0,F,[],1537,0,0,0,Dq,0,F,[CA],1537,0,0,0,CZ,0,F,[],1537,0,0,0,CX,0,F,[Dq,CZ],17,0,0,0,DA,0,F,[],17,0,()=>Ba(),0,EI,0,F,[],17,0,0,0,Ei,0,F,[],17,0,0,0,EV,0,F,[],
17,0,0,0,Dx,0,F,[],1537,0,0,0,DE,0,F,[Dx],1,0,0,0,Cp,0,F,[BF],1,0,()=>Cm(),0,DR,0,F,[],17,0,0,0,Ev,0,F,[],17,0,0,0,DW,0,F,[],16,0,0,0,De,0,F,[],16,0,0,0,Cd,0,F,[],16,0,()=>R(),0,Bl,0,L,[],1,0,0,0,BU,0,BA,[BF],1,0,()=>Bs(),0,CG,0,F,[],1536,0,0,0,Ds,0,F,[CG],1,0,0,0,D3,0,F,[],16,0,0,0,Ec,0,F,[],17,0,0,0,D_,0,F,[],17,0,0,0,Dr,0,F,[],1537,0,0,0,B5,0,F,[Dr],1025,0,0,0,Cl,0,F,[],1537,0,0,0,Cz,0,B5,[Cl,By],1,0,0,0,E0,0,L,[],1,0,0,0,Dc,0,L,[],1,0,0,0,DY,0,F,[],17,0,0,0,BX,0,L,[],1,0,0,0,BP,0,F,[],16,0,0,0,BJ,0,L,[],
1,0,0,0,W,0,BJ,[],1,0,0,0]);
C_([Ch,0,F,[],16,0,0,0,BY,0,Bl,[],1,0,0,0,CM,0,F,[],1537,0,0,0,B4,0,F,[CM,Cl],0,0,0,0,B3,0,B4,[],0,0,0,0,E5,0,F,[],1,0,0,0]);
let Ef=M(Ct),EF=M(CH),Ex=M(DP),Eo=M(EC),Dz=M(B2),D9=M(DC),Dk=M(Cf);
Ey(["0","<java_object>@","null","String is null","String is empty","String contains invalid digits: ","String contains digits out of radix ",": ","The value is too big for long type","The value is too big for long type: ","Illegal radix: ","Either src or dest is null"]);
S.prototype.toString=function(){return C6(this);};
S.prototype.valueOf=S.prototype.toString;F.prototype.toString=function(){return C6(EM(this));};
F.prototype.__teavm_class__=function(){return EG(this);};
let E9=Symbol('jsoClass');
(()=>{let c;})();
moonChunk=C;moonLod=D;moonHeight=E;})();